
module window {
    interface [

               ] NavEvent {

        readonly attribute DOMString propertyset; // Properties sent from event device in XML

        readonly attribute DOMString uuid; // device id

        readonly attribute DOMString friendlyName;

        readonly attribute DOMString serviceType;
    };
}
