module core {
	interface [
	           OmitConstructor
	           ] NavService	{

	    readonly attribute DOMString name;
	    readonly attribute DOMString url;
	    readonly attribute DOMString eventUrl;
	    readonly attribute DOMString uuid;
	    readonly attribute DOMString config;
	    readonly attribute DOMString serviceType;

	};
}
