module core {
	interface [
	           OmitConstructor
	           ] NavServices
	{

		// NavigatorNetworkService item(index)
		[Custom] void item(in unsigned long index);

		readonly attribute unsigned long length;

		readonly attribute unsigned short servicesAvailable;

	};
}
