/*
    This file is part of the WebKit open source project.
    This file has been generated by generate-bindings.pl. DO NOT MODIFY!

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB.  If not, write to
    the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
    Boston, MA 02110-1301, USA.
*/

#include <glib-object.h>
#include "config.h"

#include <wtf/GetPtr.h>
#include <wtf/RefPtr.h>
#include "DOMObjectCache.h"
#include "ExceptionCode.h"
#include "JSMainThreadExecState.h"
#include "NodeFilter.h"
#include "WebKitDOMBinding.h"
#include "gobject/ConvertToUTF8String.h"
#include "webkit/WebKitDOMNode.h"
#include "webkit/WebKitDOMNodeFilter.h"
#include "webkit/WebKitDOMNodeFilterPrivate.h"
#include "webkit/WebKitDOMNodePrivate.h"
#include "webkitdefines.h"
#include "webkitglobalsprivate.h"
#include "webkitmarshal.h"

namespace WebKit {

WebKitDOMNodeFilter* kit(WebCore::NodeFilter* obj)
{
    g_return_val_if_fail(obj, 0);

    if (gpointer ret = DOMObjectCache::get(obj))
        return static_cast<WebKitDOMNodeFilter*>(ret);

    return static_cast<WebKitDOMNodeFilter*>(DOMObjectCache::put(obj, WebKit::wrapNodeFilter(obj)));
}

WebCore::NodeFilter* core(WebKitDOMNodeFilter* request)
{
    g_return_val_if_fail(request, 0);

    WebCore::NodeFilter* coreObject = static_cast<WebCore::NodeFilter*>(WEBKIT_DOM_OBJECT(request)->coreObject);
    g_return_val_if_fail(coreObject, 0);

    return coreObject;
}

WebKitDOMNodeFilter* wrapNodeFilter(WebCore::NodeFilter* coreObject)
{
    g_return_val_if_fail(coreObject, 0);

    /* We call ref() rather than using a C++ smart pointer because we can't store a C++ object
     * in a C-allocated GObject structure.  See the finalize() code for the
     * matching deref().
     */
    coreObject->ref();

    return  WEBKIT_DOM_NODE_FILTER(g_object_new(WEBKIT_TYPE_DOM_NODE_FILTER,
                                               "core-object", coreObject, NULL));
}

} // namespace WebKit

G_DEFINE_TYPE(WebKitDOMNodeFilter, webkit_dom_node_filter, WEBKIT_TYPE_DOM_OBJECT)

enum {
    PROP_0,
};

static void webkit_dom_node_filter_finalize(GObject* object)
{

    WebKitDOMObject* dom_object = WEBKIT_DOM_OBJECT(object);
    
    if (dom_object->coreObject) {
        WebCore::NodeFilter* coreObject = static_cast<WebCore::NodeFilter *>(dom_object->coreObject);

        WebKit::DOMObjectCache::forget(coreObject);
        coreObject->deref();

        dom_object->coreObject = NULL;
    }


    G_OBJECT_CLASS(webkit_dom_node_filter_parent_class)->finalize(object);
}

static void webkit_dom_node_filter_set_property(GObject* object, guint prop_id, const GValue* value, GParamSpec* pspec)
{
    WebCore::JSMainThreadNullState state;
    switch (prop_id) {
    default:
        G_OBJECT_WARN_INVALID_PROPERTY_ID(object, prop_id, pspec);
        break;
    }
}


static void webkit_dom_node_filter_get_property(GObject* object, guint prop_id, GValue* value, GParamSpec* pspec)
{
    WebCore::JSMainThreadNullState state;
    switch (prop_id) {
    default:
        G_OBJECT_WARN_INVALID_PROPERTY_ID(object, prop_id, pspec);
        break;
    }
}


static void webkit_dom_node_filter_constructed(GObject* object)
{

    if (G_OBJECT_CLASS(webkit_dom_node_filter_parent_class)->constructed)
        G_OBJECT_CLASS(webkit_dom_node_filter_parent_class)->constructed(object);
}

static void webkit_dom_node_filter_class_init(WebKitDOMNodeFilterClass* requestClass)
{
    GObjectClass *gobjectClass = G_OBJECT_CLASS(requestClass);
    gobjectClass->finalize = webkit_dom_node_filter_finalize;
    gobjectClass->set_property = webkit_dom_node_filter_set_property;
    gobjectClass->get_property = webkit_dom_node_filter_get_property;
    gobjectClass->constructed = webkit_dom_node_filter_constructed;



}

static void webkit_dom_node_filter_init(WebKitDOMNodeFilter* request)
{
}

gshort
webkit_dom_node_filter_accept_node(WebKitDOMNodeFilter* self, WebKitDOMNode* n)
{
    g_return_val_if_fail(self, 0);
    WebCore::JSMainThreadNullState state;
    WebCore::NodeFilter * item = WebKit::core(self);
    g_return_val_if_fail(n, 0);
    WebCore::Node * converted_n = NULL;
    if (n != NULL) {
        converted_n = WebKit::core(n);
        g_return_val_if_fail(converted_n, 0);
    }
    gshort res = item->acceptNode(converted_n);
    return res;
}

