/*
    This file is part of the WebKit open source project.
    This file has been generated by generate-bindings.pl. DO NOT MODIFY!

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB.  If not, write to
    the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
    Boston, MA 02110-1301, USA.
*/

#include <glib-object.h>
#include "config.h"

#include <wtf/GetPtr.h>
#include <wtf/RefPtr.h>
#include "DOMObjectCache.h"
#include "ExceptionCode.h"
#include "JSMainThreadExecState.h"
#include "NodeList.h"
#include "WebKitDOMBinding.h"
#include "WebKitNamedFlow.h"
#include "gobject/ConvertToUTF8String.h"
#include "webkit/WebKitDOMNode.h"
#include "webkit/WebKitDOMNodeList.h"
#include "webkit/WebKitDOMNodeListPrivate.h"
#include "webkit/WebKitDOMNodePrivate.h"
#include "webkit/WebKitDOMWebKitNamedFlow.h"
#include "webkit/WebKitDOMWebKitNamedFlowPrivate.h"
#include "webkitdefines.h"
#include "webkitglobalsprivate.h"
#include "webkitmarshal.h"

namespace WebKit {

WebKitDOMWebKitNamedFlow* kit(WebCore::WebKitNamedFlow* obj)
{
    g_return_val_if_fail(obj, 0);

    if (gpointer ret = DOMObjectCache::get(obj))
        return static_cast<WebKitDOMWebKitNamedFlow*>(ret);

    return static_cast<WebKitDOMWebKitNamedFlow*>(DOMObjectCache::put(obj, WebKit::wrapWebKitNamedFlow(obj)));
}

WebCore::WebKitNamedFlow* core(WebKitDOMWebKitNamedFlow* request)
{
    g_return_val_if_fail(request, 0);

    WebCore::WebKitNamedFlow* coreObject = static_cast<WebCore::WebKitNamedFlow*>(WEBKIT_DOM_OBJECT(request)->coreObject);
    g_return_val_if_fail(coreObject, 0);

    return coreObject;
}

WebKitDOMWebKitNamedFlow* wrapWebKitNamedFlow(WebCore::WebKitNamedFlow* coreObject)
{
    g_return_val_if_fail(coreObject, 0);

    /* We call ref() rather than using a C++ smart pointer because we can't store a C++ object
     * in a C-allocated GObject structure.  See the finalize() code for the
     * matching deref().
     */
    coreObject->ref();

    return  WEBKIT_DOM_WEBKIT_NAMED_FLOW(g_object_new(WEBKIT_TYPE_DOM_WEBKIT_NAMED_FLOW,
                                               "core-object", coreObject, NULL));
}

} // namespace WebKit

G_DEFINE_TYPE(WebKitDOMWebKitNamedFlow, webkit_dom_webkit_named_flow, WEBKIT_TYPE_DOM_OBJECT)

enum {
    PROP_0,
    PROP_OVERFLOW,
};

static void webkit_dom_webkit_named_flow_finalize(GObject* object)
{

    WebKitDOMObject* dom_object = WEBKIT_DOM_OBJECT(object);
    
    if (dom_object->coreObject) {
        WebCore::WebKitNamedFlow* coreObject = static_cast<WebCore::WebKitNamedFlow *>(dom_object->coreObject);

        WebKit::DOMObjectCache::forget(coreObject);
        coreObject->deref();

        dom_object->coreObject = NULL;
    }


    G_OBJECT_CLASS(webkit_dom_webkit_named_flow_parent_class)->finalize(object);
}

static void webkit_dom_webkit_named_flow_set_property(GObject* object, guint prop_id, const GValue* value, GParamSpec* pspec)
{
    WebCore::JSMainThreadNullState state;
    switch (prop_id) {
    default:
        G_OBJECT_WARN_INVALID_PROPERTY_ID(object, prop_id, pspec);
        break;
    }
}


static void webkit_dom_webkit_named_flow_get_property(GObject* object, guint prop_id, GValue* value, GParamSpec* pspec)
{
    WebCore::JSMainThreadNullState state;
    WebKitDOMWebKitNamedFlow* self = WEBKIT_DOM_WEBKIT_NAMED_FLOW(object);
    WebCore::WebKitNamedFlow* coreSelf = WebKit::core(self);
    switch (prop_id) {
    case PROP_OVERFLOW:
    {
        g_value_set_boolean(value, coreSelf->overflow());
        break;
    }
    default:
        G_OBJECT_WARN_INVALID_PROPERTY_ID(object, prop_id, pspec);
        break;
    }
}


static void webkit_dom_webkit_named_flow_constructed(GObject* object)
{

    if (G_OBJECT_CLASS(webkit_dom_webkit_named_flow_parent_class)->constructed)
        G_OBJECT_CLASS(webkit_dom_webkit_named_flow_parent_class)->constructed(object);
}

static void webkit_dom_webkit_named_flow_class_init(WebKitDOMWebKitNamedFlowClass* requestClass)
{
    GObjectClass *gobjectClass = G_OBJECT_CLASS(requestClass);
    gobjectClass->finalize = webkit_dom_webkit_named_flow_finalize;
    gobjectClass->set_property = webkit_dom_webkit_named_flow_set_property;
    gobjectClass->get_property = webkit_dom_webkit_named_flow_get_property;
    gobjectClass->constructed = webkit_dom_webkit_named_flow_constructed;

    g_object_class_install_property(gobjectClass,
                                    PROP_OVERFLOW,
                                    g_param_spec_boolean("overflow", /* name */
                                                           "web_kit_named_flow_overflow", /* short description */
                                                           "read-only  gboolean WebKitNamedFlow.overflow", /* longer - could do with some extra doc stuff here */
                                                           FALSE, /* default */
                                                           WEBKIT_PARAM_READABLE));


}

static void webkit_dom_webkit_named_flow_init(WebKitDOMWebKitNamedFlow* request)
{
}

WebKitDOMNodeList*
webkit_dom_webkit_named_flow_get_regions_by_content_node(WebKitDOMWebKitNamedFlow* self, WebKitDOMNode* content_node)
{
    g_return_val_if_fail(self, 0);
    WebCore::JSMainThreadNullState state;
    WebCore::WebKitNamedFlow * item = WebKit::core(self);
    g_return_val_if_fail(content_node, 0);
    WebCore::Node * converted_content_node = NULL;
    if (content_node != NULL) {
        converted_content_node = WebKit::core(content_node);
        g_return_val_if_fail(converted_content_node, 0);
    }
    PassRefPtr<WebCore::NodeList> g_res = WTF::getPtr(item->getRegionsByContentNode(converted_content_node));
    WebKitDOMNodeList* res = WebKit::kit(g_res.get());
    return res;
}

gboolean
webkit_dom_webkit_named_flow_get_overflow(WebKitDOMWebKitNamedFlow* self)
{
    g_return_val_if_fail(self, 0);
    WebCore::JSMainThreadNullState state;
    WebCore::WebKitNamedFlow * item = WebKit::core(self);
    gboolean res = item->overflow();
    return res;
}

