/*
    This file is part of the WebKit open source project.
    This file has been generated by generate-bindings.pl. DO NOT MODIFY!

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB.  If not, write to
    the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
    Boston, MA 02110-1301, USA.
*/

#include <glib-object.h>
#include "config.h"

#include <wtf/GetPtr.h>
#include <wtf/RefPtr.h>
#include "DOMObjectCache.h"
#include "ExceptionCode.h"
#include "JSMainThreadExecState.h"
#include "StyleSheet.h"
#include "StyleSheetList.h"
#include "WebKitDOMBinding.h"
#include "gobject/ConvertToUTF8String.h"
#include "webkit/WebKitDOMStyleSheet.h"
#include "webkit/WebKitDOMStyleSheetList.h"
#include "webkit/WebKitDOMStyleSheetListPrivate.h"
#include "webkit/WebKitDOMStyleSheetPrivate.h"
#include "webkitdefines.h"
#include "webkitglobalsprivate.h"
#include "webkitmarshal.h"

namespace WebKit {

WebKitDOMStyleSheetList* kit(WebCore::StyleSheetList* obj)
{
    g_return_val_if_fail(obj, 0);

    if (gpointer ret = DOMObjectCache::get(obj))
        return static_cast<WebKitDOMStyleSheetList*>(ret);

    return static_cast<WebKitDOMStyleSheetList*>(DOMObjectCache::put(obj, WebKit::wrapStyleSheetList(obj)));
}

WebCore::StyleSheetList* core(WebKitDOMStyleSheetList* request)
{
    g_return_val_if_fail(request, 0);

    WebCore::StyleSheetList* coreObject = static_cast<WebCore::StyleSheetList*>(WEBKIT_DOM_OBJECT(request)->coreObject);
    g_return_val_if_fail(coreObject, 0);

    return coreObject;
}

WebKitDOMStyleSheetList* wrapStyleSheetList(WebCore::StyleSheetList* coreObject)
{
    g_return_val_if_fail(coreObject, 0);

    /* We call ref() rather than using a C++ smart pointer because we can't store a C++ object
     * in a C-allocated GObject structure.  See the finalize() code for the
     * matching deref().
     */
    coreObject->ref();

    return  WEBKIT_DOM_STYLE_SHEET_LIST(g_object_new(WEBKIT_TYPE_DOM_STYLE_SHEET_LIST,
                                               "core-object", coreObject, NULL));
}

} // namespace WebKit

G_DEFINE_TYPE(WebKitDOMStyleSheetList, webkit_dom_style_sheet_list, WEBKIT_TYPE_DOM_OBJECT)

enum {
    PROP_0,
    PROP_LENGTH,
};

static void webkit_dom_style_sheet_list_finalize(GObject* object)
{

    WebKitDOMObject* dom_object = WEBKIT_DOM_OBJECT(object);
    
    if (dom_object->coreObject) {
        WebCore::StyleSheetList* coreObject = static_cast<WebCore::StyleSheetList *>(dom_object->coreObject);

        WebKit::DOMObjectCache::forget(coreObject);
        coreObject->deref();

        dom_object->coreObject = NULL;
    }


    G_OBJECT_CLASS(webkit_dom_style_sheet_list_parent_class)->finalize(object);
}

static void webkit_dom_style_sheet_list_set_property(GObject* object, guint prop_id, const GValue* value, GParamSpec* pspec)
{
    WebCore::JSMainThreadNullState state;
    switch (prop_id) {
    default:
        G_OBJECT_WARN_INVALID_PROPERTY_ID(object, prop_id, pspec);
        break;
    }
}


static void webkit_dom_style_sheet_list_get_property(GObject* object, guint prop_id, GValue* value, GParamSpec* pspec)
{
    WebCore::JSMainThreadNullState state;
    WebKitDOMStyleSheetList* self = WEBKIT_DOM_STYLE_SHEET_LIST(object);
    WebCore::StyleSheetList* coreSelf = WebKit::core(self);
    switch (prop_id) {
    case PROP_LENGTH:
    {
        g_value_set_ulong(value, coreSelf->length());
        break;
    }
    default:
        G_OBJECT_WARN_INVALID_PROPERTY_ID(object, prop_id, pspec);
        break;
    }
}


static void webkit_dom_style_sheet_list_constructed(GObject* object)
{

    if (G_OBJECT_CLASS(webkit_dom_style_sheet_list_parent_class)->constructed)
        G_OBJECT_CLASS(webkit_dom_style_sheet_list_parent_class)->constructed(object);
}

static void webkit_dom_style_sheet_list_class_init(WebKitDOMStyleSheetListClass* requestClass)
{
    GObjectClass *gobjectClass = G_OBJECT_CLASS(requestClass);
    gobjectClass->finalize = webkit_dom_style_sheet_list_finalize;
    gobjectClass->set_property = webkit_dom_style_sheet_list_set_property;
    gobjectClass->get_property = webkit_dom_style_sheet_list_get_property;
    gobjectClass->constructed = webkit_dom_style_sheet_list_constructed;

    g_object_class_install_property(gobjectClass,
                                    PROP_LENGTH,
                                    g_param_spec_ulong("length", /* name */
                                                           "style_sheet_list_length", /* short description */
                                                           "read-only  gulong StyleSheetList.length", /* longer - could do with some extra doc stuff here */
                                                           0, /* min */
G_MAXULONG, /* max */
0, /* default */
                                                           WEBKIT_PARAM_READABLE));


}

static void webkit_dom_style_sheet_list_init(WebKitDOMStyleSheetList* request)
{
}

WebKitDOMStyleSheet*
webkit_dom_style_sheet_list_item(WebKitDOMStyleSheetList* self, gulong index)
{
    g_return_val_if_fail(self, 0);
    WebCore::JSMainThreadNullState state;
    WebCore::StyleSheetList * item = WebKit::core(self);
    PassRefPtr<WebCore::StyleSheet> g_res = WTF::getPtr(item->item(index));
    WebKitDOMStyleSheet* res = WebKit::kit(g_res.get());
    return res;
}

gulong
webkit_dom_style_sheet_list_get_length(WebKitDOMStyleSheetList* self)
{
    g_return_val_if_fail(self, 0);
    WebCore::JSMainThreadNullState state;
    WebCore::StyleSheetList * item = WebKit::core(self);
    gulong res = item->length();
    return res;
}

