/* C++ code produced by gperf version 3.0.3 */
/* Command-line: gperf --key-positions='*' -D -n -s 2 --output-file=CSSPropertyNames.cpp CSSPropertyNames.gperf  */

#if !((' ' == 32) && ('!' == 33) && ('"' == 34) && ('#' == 35) \
      && ('%' == 37) && ('&' == 38) && ('\'' == 39) && ('(' == 40) \
      && (')' == 41) && ('*' == 42) && ('+' == 43) && (',' == 44) \
      && ('-' == 45) && ('.' == 46) && ('/' == 47) && ('0' == 48) \
      && ('1' == 49) && ('2' == 50) && ('3' == 51) && ('4' == 52) \
      && ('5' == 53) && ('6' == 54) && ('7' == 55) && ('8' == 56) \
      && ('9' == 57) && (':' == 58) && (';' == 59) && ('<' == 60) \
      && ('=' == 61) && ('>' == 62) && ('?' == 63) && ('A' == 65) \
      && ('B' == 66) && ('C' == 67) && ('D' == 68) && ('E' == 69) \
      && ('F' == 70) && ('G' == 71) && ('H' == 72) && ('I' == 73) \
      && ('J' == 74) && ('K' == 75) && ('L' == 76) && ('M' == 77) \
      && ('N' == 78) && ('O' == 79) && ('P' == 80) && ('Q' == 81) \
      && ('R' == 82) && ('S' == 83) && ('T' == 84) && ('U' == 85) \
      && ('V' == 86) && ('W' == 87) && ('X' == 88) && ('Y' == 89) \
      && ('Z' == 90) && ('[' == 91) && ('\\' == 92) && (']' == 93) \
      && ('^' == 94) && ('_' == 95) && ('a' == 97) && ('b' == 98) \
      && ('c' == 99) && ('d' == 100) && ('e' == 101) && ('f' == 102) \
      && ('g' == 103) && ('h' == 104) && ('i' == 105) && ('j' == 106) \
      && ('k' == 107) && ('l' == 108) && ('m' == 109) && ('n' == 110) \
      && ('o' == 111) && ('p' == 112) && ('q' == 113) && ('r' == 114) \
      && ('s' == 115) && ('t' == 116) && ('u' == 117) && ('v' == 118) \
      && ('w' == 119) && ('x' == 120) && ('y' == 121) && ('z' == 122) \
      && ('{' == 123) && ('|' == 124) && ('}' == 125) && ('~' == 126))
/* The character set is not based on ISO-646.  */
#error "gperf generated tables don't work with this execution character set. Please report a bug to <bug-gnu-gperf@gnu.org>."
#endif

#line 1 "CSSPropertyNames.gperf"

/* This file is automatically generated from CSSPropertyNames.in by makeprop, do not edit */
#include "config.h"
#include "CSSPropertyNames.h"
#include "HashTools.h"
#include <string.h>

#include <wtf/ASCIICType.h>
#include <wtf/text/WTFString.h>

namespace WebCore {
enum
  {
    TOTAL_KEYWORDS = 385,
    MIN_WORD_LENGTH = 3,
    MAX_WORD_LENGTH = 43,
    MIN_HASH_VALUE = 21,
    MAX_HASH_VALUE = 5006
  };

/* maximum key range = 4986, duplicates = 0 */

class CSSPropertyNamesHash
{
private:
  static inline unsigned int propery_hash_function (const char *str, unsigned int len);
public:
  static const struct Property *findPropertyImpl (const char *str, unsigned int len);
};

inline unsigned int
CSSPropertyNamesHash::propery_hash_function (register const char *str, register unsigned int len)
{
  static const unsigned short asso_values[] =
    {
      5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007,
      5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007,
      5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007,
      5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007,
      5007, 5007, 5007, 5007, 5007,    0, 5007, 5007, 5007, 5007,
      5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007,
      5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007,
      5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007,
      5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007,
      5007, 5007, 5007, 5007, 5007, 5007, 5007,    5,    0,  555,
         0,    5,    1,   55,  291,    0,    0,    0,  495,   95,
        10,   10,  215,   10,   15,  290,    0,  960,  120,    0,
       646,  536,   70, 5007, 5007, 5007, 5007, 5007, 5007, 5007,
      5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007,
      5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007,
      5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007,
      5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007,
      5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007,
      5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007,
      5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007,
      5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007,
      5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007,
      5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007,
      5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007,
      5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007, 5007,
      5007, 5007, 5007, 5007, 5007, 5007
    };
  register int hval = 0;

  switch (len)
    {
      default:
        hval += asso_values[(unsigned char)str[42]];
      /*FALLTHROUGH*/
      case 42:
        hval += asso_values[(unsigned char)str[41]];
      /*FALLTHROUGH*/
      case 41:
        hval += asso_values[(unsigned char)str[40]];
      /*FALLTHROUGH*/
      case 40:
        hval += asso_values[(unsigned char)str[39]];
      /*FALLTHROUGH*/
      case 39:
        hval += asso_values[(unsigned char)str[38]];
      /*FALLTHROUGH*/
      case 38:
        hval += asso_values[(unsigned char)str[37]];
      /*FALLTHROUGH*/
      case 37:
        hval += asso_values[(unsigned char)str[36]];
      /*FALLTHROUGH*/
      case 36:
        hval += asso_values[(unsigned char)str[35]];
      /*FALLTHROUGH*/
      case 35:
        hval += asso_values[(unsigned char)str[34]];
      /*FALLTHROUGH*/
      case 34:
        hval += asso_values[(unsigned char)str[33]];
      /*FALLTHROUGH*/
      case 33:
        hval += asso_values[(unsigned char)str[32]];
      /*FALLTHROUGH*/
      case 32:
        hval += asso_values[(unsigned char)str[31]];
      /*FALLTHROUGH*/
      case 31:
        hval += asso_values[(unsigned char)str[30]];
      /*FALLTHROUGH*/
      case 30:
        hval += asso_values[(unsigned char)str[29]];
      /*FALLTHROUGH*/
      case 29:
        hval += asso_values[(unsigned char)str[28]];
      /*FALLTHROUGH*/
      case 28:
        hval += asso_values[(unsigned char)str[27]];
      /*FALLTHROUGH*/
      case 27:
        hval += asso_values[(unsigned char)str[26]];
      /*FALLTHROUGH*/
      case 26:
        hval += asso_values[(unsigned char)str[25]];
      /*FALLTHROUGH*/
      case 25:
        hval += asso_values[(unsigned char)str[24]];
      /*FALLTHROUGH*/
      case 24:
        hval += asso_values[(unsigned char)str[23]];
      /*FALLTHROUGH*/
      case 23:
        hval += asso_values[(unsigned char)str[22]];
      /*FALLTHROUGH*/
      case 22:
        hval += asso_values[(unsigned char)str[21]];
      /*FALLTHROUGH*/
      case 21:
        hval += asso_values[(unsigned char)str[20]];
      /*FALLTHROUGH*/
      case 20:
        hval += asso_values[(unsigned char)str[19]];
      /*FALLTHROUGH*/
      case 19:
        hval += asso_values[(unsigned char)str[18]];
      /*FALLTHROUGH*/
      case 18:
        hval += asso_values[(unsigned char)str[17]];
      /*FALLTHROUGH*/
      case 17:
        hval += asso_values[(unsigned char)str[16]];
      /*FALLTHROUGH*/
      case 16:
        hval += asso_values[(unsigned char)str[15]];
      /*FALLTHROUGH*/
      case 15:
        hval += asso_values[(unsigned char)str[14]];
      /*FALLTHROUGH*/
      case 14:
        hval += asso_values[(unsigned char)str[13]];
      /*FALLTHROUGH*/
      case 13:
        hval += asso_values[(unsigned char)str[12]];
      /*FALLTHROUGH*/
      case 12:
        hval += asso_values[(unsigned char)str[11]];
      /*FALLTHROUGH*/
      case 11:
        hval += asso_values[(unsigned char)str[10]];
      /*FALLTHROUGH*/
      case 10:
        hval += asso_values[(unsigned char)str[9]];
      /*FALLTHROUGH*/
      case 9:
        hval += asso_values[(unsigned char)str[8]];
      /*FALLTHROUGH*/
      case 8:
        hval += asso_values[(unsigned char)str[7]];
      /*FALLTHROUGH*/
      case 7:
        hval += asso_values[(unsigned char)str[6]];
      /*FALLTHROUGH*/
      case 6:
        hval += asso_values[(unsigned char)str[5]];
      /*FALLTHROUGH*/
      case 5:
        hval += asso_values[(unsigned char)str[4]];
      /*FALLTHROUGH*/
      case 4:
        hval += asso_values[(unsigned char)str[3]];
      /*FALLTHROUGH*/
      case 3:
        hval += asso_values[(unsigned char)str[2]];
      /*FALLTHROUGH*/
      case 2:
        hval += asso_values[(unsigned char)str[1]];
      /*FALLTHROUGH*/
      case 1:
        hval += asso_values[(unsigned char)str[0]];
        break;
    }
  return hval;
}

static const struct Property property_wordlist[] =
  {
#line 29 "CSSPropertyNames.gperf"
    {"font", CSSPropertyFont},
#line 59 "CSSPropertyNames.gperf"
    {"border", CSSPropertyBorder},
#line 179 "CSSPropertyNames.gperf"
    {"word-break", CSSPropertyWordBreak},
#line 211 "CSSPropertyNames.gperf"
    {"-webkit-border-fit", CSSPropertyWebkitBorderFit},
#line 207 "CSSPropertyNames.gperf"
    {"-webkit-border-end", CSSPropertyWebkitBorderEnd},
#line 199 "CSSPropertyNames.gperf"
    {"-webkit-border-after", CSSPropertyWebkitBorderAfter},
#line 203 "CSSPropertyNames.gperf"
    {"-webkit-border-before", CSSPropertyWebkitBorderBefore},
#line 390 "CSSPropertyNames.gperf"
    {"kerning", CSSPropertyKerning},
#line 92 "CSSPropertyNames.gperf"
    {"bottom", CSSPropertyBottom},
#line 37 "CSSPropertyNames.gperf"
    {"-webkit-font-kerning", CSSPropertyWebkitFontKerning},
#line 372 "CSSPropertyNames.gperf"
    {"marker", CSSPropertyMarker},
#line 183 "CSSPropertyNames.gperf"
    {"-webkit-animation", CSSPropertyWebkitAnimation},
#line 373 "CSSPropertyNames.gperf"
    {"marker-end", CSSPropertyMarkerEnd},
#line 349 "CSSPropertyNames.gperf"
    {"-webkit-region-break-after", CSSPropertyWebkitRegionBreakAfter},
#line 60 "CSSPropertyNames.gperf"
    {"border-bottom", CSSPropertyBorderBottom},
#line 350 "CSSPropertyNames.gperf"
    {"-webkit-region-break-before", CSSPropertyWebkitRegionBreakBefore},
#line 33 "CSSPropertyNames.gperf"
    {"font-variant", CSSPropertyFontVariant},
#line 113 "CSSPropertyNames.gperf"
    {"margin", CSSPropertyMargin},
#line 44 "CSSPropertyNames.gperf"
    {"zoom", CSSPropertyZoom},
#line 393 "CSSPropertyNames.gperf"
    {"writing-mode", CSSPropertyWritingMode},
#line 43 "CSSPropertyNames.gperf"
    {"-webkit-writing-mode", CSSPropertyWebkitWritingMode},
#line 274 "CSSPropertyNames.gperf"
    {"-webkit-margin-end", CSSPropertyWebkitMarginEnd},
#line 68 "CSSPropertyNames.gperf"
    {"border-image", CSSPropertyBorderImage},
#line 213 "CSSPropertyNames.gperf"
    {"-webkit-border-image", CSSPropertyWebkitBorderImage},
#line 272 "CSSPropertyNames.gperf"
    {"-webkit-margin-after", CSSPropertyWebkitMarginAfter},
#line 273 "CSSPropertyNames.gperf"
    {"-webkit-margin-before", CSSPropertyWebkitMarginBefore},
#line 171 "CSSPropertyNames.gperf"
    {"top", CSSPropertyTop},
#line 374 "CSSPropertyNames.gperf"
    {"marker-mid", CSSPropertyMarkerMid},
#line 354 "CSSPropertyNames.gperf"
    {"-webkit-wrap", CSSPropertyWebkitWrap},
#line 189 "CSSPropertyNames.gperf"
    {"-webkit-animation-name", CSSPropertyWebkitAnimationName},
#line 181 "CSSPropertyNames.gperf"
    {"word-wrap", CSSPropertyWordWrap},
#line 85 "CSSPropertyNames.gperf"
    {"border-top", CSSPropertyBorderTop},
#line 106 "CSSPropertyNames.gperf"
    {"image-rendering", CSSPropertyImageRendering},
#line 137 "CSSPropertyNames.gperf"
    {"page", CSSPropertyPage},
#line 132 "CSSPropertyNames.gperf"
    {"padding", CSSPropertyPadding},
#line 178 "CSSPropertyNames.gperf"
    {"width", CSSPropertyWidth},
#line 114 "CSSPropertyNames.gperf"
    {"margin-bottom", CSSPropertyMarginBottom},
#line 177 "CSSPropertyNames.gperf"
    {"widows", CSSPropertyWidows},
#line 309 "CSSPropertyNames.gperf"
    {"-webkit-padding-end", CSSPropertyWebkitPaddingEnd},
#line 307 "CSSPropertyNames.gperf"
    {"-webkit-padding-after", CSSPropertyWebkitPaddingAfter},
#line 377 "CSSPropertyNames.gperf"
    {"stroke", CSSPropertyStroke},
#line 308 "CSSPropertyNames.gperf"
    {"-webkit-padding-before", CSSPropertyWebkitPaddingBefore},
#line 138 "CSSPropertyNames.gperf"
    {"page-break-after", CSSPropertyPageBreakAfter},
#line 91 "CSSPropertyNames.gperf"
    {"border-width", CSSPropertyBorderWidth},
#line 139 "CSSPropertyNames.gperf"
    {"page-break-before", CSSPropertyPageBreakBefore},
#line 334 "CSSPropertyNames.gperf"
    {"-webkit-transition", CSSPropertyWebkitTransition},
#line 210 "CSSPropertyNames.gperf"
    {"-webkit-border-end-width", CSSPropertyWebkitBorderEndWidth},
#line 215 "CSSPropertyNames.gperf"
    {"-webkit-border-start", CSSPropertyWebkitBorderStart},
#line 145 "CSSPropertyNames.gperf"
    {"right", CSSPropertyRight},
#line 146 "CSSPropertyNames.gperf"
    {"size", CSSPropertySize},
#line 202 "CSSPropertyNames.gperf"
    {"-webkit-border-after-width", CSSPropertyWebkitBorderAfterWidth},
#line 34 "CSSPropertyNames.gperf"
    {"font-weight", CSSPropertyFontWeight},
#line 206 "CSSPropertyNames.gperf"
    {"-webkit-border-before-width", CSSPropertyWebkitBorderBeforeWidth},
#line 144 "CSSPropertyNames.gperf"
    {"resize", CSSPropertyResize},
#line 31 "CSSPropertyNames.gperf"
    {"font-size", CSSPropertyFontSize},
#line 357 "CSSPropertyNames.gperf"
    {"mask", CSSPropertyMask},
#line 282 "CSSPropertyNames.gperf"
    {"-webkit-mask", CSSPropertyWebkitMask},
#line 121 "CSSPropertyNames.gperf"
    {"min-width", CSSPropertyMinWidth},
#line 133 "CSSPropertyNames.gperf"
    {"padding-bottom", CSSPropertyPaddingBottom},
#line 117 "CSSPropertyNames.gperf"
    {"margin-top", CSSPropertyMarginTop},
#line 79 "CSSPropertyNames.gperf"
    {"border-right", CSSPropertyBorderRight},
#line 347 "CSSPropertyNames.gperf"
    {"-webkit-wrap-margin", CSSPropertyWebkitWrapMargin},
#line 351 "CSSPropertyNames.gperf"
    {"-webkit-region-break-inside", CSSPropertyWebkitRegionBreakInside},
#line 375 "CSSPropertyNames.gperf"
    {"marker-start", CSSPropertyMarkerStart},
#line 328 "CSSPropertyNames.gperf"
    {"-webkit-transform", CSSPropertyWebkitTransform},
#line 70 "CSSPropertyNames.gperf"
    {"border-image-repeat", CSSPropertyBorderImageRepeat},
#line 65 "CSSPropertyNames.gperf"
    {"border-bottom-width", CSSPropertyBorderBottomWidth},
#line 293 "CSSPropertyNames.gperf"
    {"-webkit-mask-origin", CSSPropertyWebkitMaskOrigin},
#line 275 "CSSPropertyNames.gperf"
    {"-webkit-margin-start", CSSPropertyWebkitMarginStart},
#line 73 "CSSPropertyNames.gperf"
    {"border-image-width", CSSPropertyBorderImageWidth},
#line 107 "CSSPropertyNames.gperf"
    {"left", CSSPropertyLeft},
#line 136 "CSSPropertyNames.gperf"
    {"padding-top", CSSPropertyPaddingTop},
#line 103 "CSSPropertyNames.gperf"
    {"float", CSSPropertyFloat},
#line 148 "CSSPropertyNames.gperf"
    {"speak", CSSPropertySpeak},
#line 359 "CSSPropertyNames.gperf"
    {"filter", CSSPropertyFilter},
#line 348 "CSSPropertyNames.gperf"
    {"-webkit-wrap-padding", CSSPropertyWebkitWrapPadding},
#line 342 "CSSPropertyNames.gperf"
    {"-webkit-flow-into", CSSPropertyWebkitFlowInto},
#line 142 "CSSPropertyNames.gperf"
    {"position", CSSPropertyPosition},
#line 329 "CSSPropertyNames.gperf"
    {"-webkit-transform-origin", CSSPropertyWebkitTransformOrigin},
#line 261 "CSSPropertyNames.gperf"
    {"-webkit-line-break", CSSPropertyWebkitLineBreak},
#line 116 "CSSPropertyNames.gperf"
    {"margin-right", CSSPropertyMarginRight},
#line 74 "CSSPropertyNames.gperf"
    {"border-left", CSSPropertyBorderLeft},
#line 292 "CSSPropertyNames.gperf"
    {"-webkit-mask-image", CSSPropertyWebkitMaskImage},
#line 90 "CSSPropertyNames.gperf"
    {"border-top-width", CSSPropertyBorderTopWidth},
#line 263 "CSSPropertyNames.gperf"
    {"-webkit-line-grid", CSSPropertyWebkitLineGrid},
#line 98 "CSSPropertyNames.gperf"
    {"content", CSSPropertyContent},
#line 27 "CSSPropertyNames.gperf"
    {"direction", CSSPropertyDirection},
#line 310 "CSSPropertyNames.gperf"
    {"-webkit-padding-start", CSSPropertyWebkitPaddingStart},
#line 332 "CSSPropertyNames.gperf"
    {"-webkit-transform-origin-z", CSSPropertyWebkitTransformOriginZ},
#line 140 "CSSPropertyNames.gperf"
    {"page-break-inside", CSSPropertyPageBreakInside},
#line 384 "CSSPropertyNames.gperf"
    {"stroke-width", CSSPropertyStrokeWidth},
#line 316 "CSSPropertyNames.gperf"
    {"-webkit-rtl-ordering", CSSPropertyWebkitRtlOrdering},
#line 306 "CSSPropertyNames.gperf"
    {"-webkit-nbsp-mode", CSSPropertyWebkitNbspMode},
#line 343 "CSSPropertyNames.gperf"
    {"-webkit-flow-from", CSSPropertyWebkitFlowFrom},
#line 297 "CSSPropertyNames.gperf"
    {"-webkit-mask-repeat", CSSPropertyWebkitMaskRepeat},
#line 105 "CSSPropertyNames.gperf"
    {"height", CSSPropertyHeight},
#line 135 "CSSPropertyNames.gperf"
    {"padding-right", CSSPropertyPaddingRight},
#line 218 "CSSPropertyNames.gperf"
    {"-webkit-border-start-width", CSSPropertyWebkitBorderStartWidth},
#line 129 "CSSPropertyNames.gperf"
    {"overflow", CSSPropertyOverflow},
#line 152 "CSSPropertyNames.gperf"
    {"text-indent", CSSPropertyTextIndent},
#line 115 "CSSPropertyNames.gperf"
    {"margin-left", CSSPropertyMarginLeft},
#line 141 "CSSPropertyNames.gperf"
    {"pointer-events", CSSPropertyPointerEvents},
#line 82 "CSSPropertyNames.gperf"
    {"border-right-width", CSSPropertyBorderRightWidth},
#line 226 "CSSPropertyNames.gperf"
    {"-webkit-box-orient", CSSPropertyWebkitBoxOrient},
#line 41 "CSSPropertyNames.gperf"
    {"-webkit-text-orientation", CSSPropertyWebkitTextOrientation},
#line 182 "CSSPropertyNames.gperf"
    {"z-index", CSSPropertyZIndex},
#line 185 "CSSPropertyNames.gperf"
    {"-webkit-animation-direction", CSSPropertyWebkitAnimationDirection},
#line 352 "CSSPropertyNames.gperf"
    {"-webkit-wrap-flow", CSSPropertyWebkitWrapFlow},
#line 120 "CSSPropertyNames.gperf"
    {"min-height", CSSPropertyMinHeight},
#line 344 "CSSPropertyNames.gperf"
    {"-webkit-region-overflow", CSSPropertyWebkitRegionOverflow},
#line 300 "CSSPropertyNames.gperf"
    {"-webkit-mask-size", CSSPropertyWebkitMaskSize},
#line 35 "CSSPropertyNames.gperf"
    {"text-rendering", CSSPropertyTextRendering},
#line 134 "CSSPropertyNames.gperf"
    {"padding-left", CSSPropertyPaddingLeft},
#line 38 "CSSPropertyNames.gperf"
    {"-webkit-font-smoothing", CSSPropertyWebkitFontSmoothing},
#line 123 "CSSPropertyNames.gperf"
    {"orphans", CSSPropertyOrphans},
#line 77 "CSSPropertyNames.gperf"
    {"border-left-width", CSSPropertyBorderLeftWidth},
#line 381 "CSSPropertyNames.gperf"
    {"stroke-linejoin", CSSPropertyStrokeLinejoin},
#line 147 "CSSPropertyNames.gperf"
    {"src", CSSPropertySrc},
#line 252 "CSSPropertyNames.gperf"
    {"-webkit-font-size-delta", CSSPropertyWebkitFontSizeDelta},
#line 376 "CSSPropertyNames.gperf"
    {"shape-rendering", CSSPropertyShapeRendering},
#line 294 "CSSPropertyNames.gperf"
    {"-webkit-mask-position", CSSPropertyWebkitMaskPosition},
#line 387 "CSSPropertyNames.gperf"
    {"dominant-baseline", CSSPropertyDominantBaseline},
#line 325 "CSSPropertyNames.gperf"
    {"-webkit-text-stroke", CSSPropertyWebkitTextStroke},
#line 369 "CSSPropertyNames.gperf"
    {"fill", CSSPropertyFill},
#line 382 "CSSPropertyNames.gperf"
    {"stroke-miterlimit", CSSPropertyStrokeMiterlimit},
#line 264 "CSSPropertyNames.gperf"
    {"-webkit-line-snap", CSSPropertyWebkitLineSnap},
#line 119 "CSSPropertyNames.gperf"
    {"max-width", CSSPropertyMaxWidth},
#line 192 "CSSPropertyNames.gperf"
    {"-webkit-appearance", CSSPropertyWebkitAppearance},
#line 394 "CSSPropertyNames.gperf"
    {"-webkit-svg-shadow", CSSPropertyWebkitSvgShadow},
#line 331 "CSSPropertyNames.gperf"
    {"-webkit-transform-origin-y", CSSPropertyWebkitTransformOriginY},
#line 96 "CSSPropertyNames.gperf"
    {"clear", CSSPropertyClear},
#line 260 "CSSPropertyNames.gperf"
    {"-webkit-line-align", CSSPropertyWebkitLineAlign},
#line 94 "CSSPropertyNames.gperf"
    {"box-sizing", CSSPropertyBoxSizing},
#line 26 "CSSPropertyNames.gperf"
    {"color", CSSPropertyColor},
#line 401 "CSSPropertyNames.gperf"
    {"-webkit-box-sizing", CSSPropertyBoxSizing},
#line 95 "CSSPropertyNames.gperf"
    {"caption-side", CSSPropertyCaptionSide},
#line 165 "CSSPropertyNames.gperf"
    {"text-transform", CSSPropertyTextTransform},
#line 276 "CSSPropertyNames.gperf"
    {"-webkit-marquee", CSSPropertyWebkitMarquee},
#line 193 "CSSPropertyNames.gperf"
    {"-webkit-aspect-ratio", CSSPropertyWebkitAspectRatio},
#line 67 "CSSPropertyNames.gperf"
    {"border-color", CSSPropertyBorderColor},
#line 186 "CSSPropertyNames.gperf"
    {"-webkit-animation-duration", CSSPropertyWebkitAnimationDuration},
#line 208 "CSSPropertyNames.gperf"
    {"-webkit-border-end-color", CSSPropertyWebkitBorderEndColor},
#line 45 "CSSPropertyNames.gperf"
    {"line-height", CSSPropertyLineHeight},
#line 30 "CSSPropertyNames.gperf"
    {"font-family", CSSPropertyFontFamily},
#line 180 "CSSPropertyNames.gperf"
    {"word-spacing", CSSPropertyWordSpacing},
#line 200 "CSSPropertyNames.gperf"
    {"-webkit-border-after-color", CSSPropertyWebkitBorderAfterColor},
#line 204 "CSSPropertyNames.gperf"
    {"-webkit-border-before-color", CSSPropertyWebkitBorderBeforeColor},
#line 83 "CSSPropertyNames.gperf"
    {"border-spacing", CSSPropertyBorderSpacing},
#line 299 "CSSPropertyNames.gperf"
    {"-webkit-mask-repeat-y", CSSPropertyWebkitMaskRepeatY},
#line 104 "CSSPropertyNames.gperf"
    {"font-stretch", CSSPropertyFontStretch},
#line 184 "CSSPropertyNames.gperf"
    {"-webkit-animation-delay", CSSPropertyWebkitAnimationDelay},
#line 330 "CSSPropertyNames.gperf"
    {"-webkit-transform-origin-x", CSSPropertyWebkitTransformOriginX},
#line 131 "CSSPropertyNames.gperf"
    {"overflow-y", CSSPropertyOverflowY},
#line 249 "CSSPropertyNames.gperf"
    {"-webkit-flex-order", CSSPropertyWebkitFlexOrder},
#line 368 "CSSPropertyNames.gperf"
    {"color-rendering", CSSPropertyColorRendering},
#line 284 "CSSPropertyNames.gperf"
    {"-webkit-mask-box-image", CSSPropertyWebkitMaskBoxImage},
#line 379 "CSSPropertyNames.gperf"
    {"stroke-dashoffset", CSSPropertyStrokeDashoffset},
#line 150 "CSSPropertyNames.gperf"
    {"text-align", CSSPropertyTextAlign},
#line 220 "CSSPropertyNames.gperf"
    {"-webkit-box-align", CSSPropertyWebkitBoxAlign},
#line 405 "CSSPropertyNames.gperf"
    {"-epub-word-break", CSSPropertyWordBreak},
#line 187 "CSSPropertyNames.gperf"
    {"-webkit-animation-fill-mode", CSSPropertyWebkitAnimationFillMode},
#line 61 "CSSPropertyNames.gperf"
    {"border-bottom-color", CSSPropertyBorderBottomColor},
#line 164 "CSSPropertyNames.gperf"
    {"text-shadow", CSSPropertyTextShadow},
#line 93 "CSSPropertyNames.gperf"
    {"box-shadow", CSSPropertyBoxShadow},
#line 221 "CSSPropertyNames.gperf"
    {"-webkit-box-direction", CSSPropertyWebkitBoxDirection},
#line 229 "CSSPropertyNames.gperf"
    {"-webkit-box-shadow", CSSPropertyWebkitBoxShadow},
#line 151 "CSSPropertyNames.gperf"
    {"text-decoration", CSSPropertyTextDecoration},
#line 97 "CSSPropertyNames.gperf"
    {"clip", CSSPropertyClip},
#line 327 "CSSPropertyNames.gperf"
    {"-webkit-text-stroke-width", CSSPropertyWebkitTextStrokeWidth},
#line 392 "CSSPropertyNames.gperf"
    {"vector-effect", CSSPropertyVectorEffect},
#line 143 "CSSPropertyNames.gperf"
    {"quotes", CSSPropertyQuotes},
#line 298 "CSSPropertyNames.gperf"
    {"-webkit-mask-repeat-x", CSSPropertyWebkitMaskRepeatX},
#line 130 "CSSPropertyNames.gperf"
    {"overflow-x", CSSPropertyOverflowX},
#line 158 "CSSPropertyNames.gperf"
    {"text-overflow", CSSPropertyTextOverflow},
#line 159 "CSSPropertyNames.gperf"
    {"text-overline", CSSPropertyTextOverline},
#line 78 "CSSPropertyNames.gperf"
    {"border-radius", CSSPropertyBorderRadius},
#line 214 "CSSPropertyNames.gperf"
    {"-webkit-border-radius", CSSPropertyWebkitBorderRadius},
#line 122 "CSSPropertyNames.gperf"
    {"opacity", CSSPropertyOpacity},
#line 403 "CSSPropertyNames.gperf"
    {"-webkit-opacity", CSSPropertyOpacity},
#line 317 "CSSPropertyNames.gperf"
    {"-webkit-text-combine", CSSPropertyWebkitTextCombine},
#line 336 "CSSPropertyNames.gperf"
    {"-webkit-transition-duration", CSSPropertyWebkitTransitionDuration},
#line 32 "CSSPropertyNames.gperf"
    {"font-style", CSSPropertyFontStyle},
#line 339 "CSSPropertyNames.gperf"
    {"-webkit-user-drag", CSSPropertyWebkitUserDrag},
#line 345 "CSSPropertyNames.gperf"
    {"-webkit-wrap-shape-inside", CSSPropertyWebkitWrapShapeInside},
#line 86 "CSSPropertyNames.gperf"
    {"border-top-color", CSSPropertyBorderTopColor},
#line 337 "CSSPropertyNames.gperf"
    {"-webkit-transition-property", CSSPropertyWebkitTransitionProperty},
#line 279 "CSSPropertyNames.gperf"
    {"-webkit-marquee-repetition", CSSPropertyWebkitMarqueeRepetition},
#line 283 "CSSPropertyNames.gperf"
    {"-webkit-mask-attachment", CSSPropertyWebkitMaskAttachment},
#line 176 "CSSPropertyNames.gperf"
    {"white-space", CSSPropertyWhiteSpace},
#line 396 "CSSPropertyNames.gperf"
    {"-epub-writing-mode", CSSPropertyWebkitWritingMode},
#line 84 "CSSPropertyNames.gperf"
    {"border-style", CSSPropertyBorderStyle},
#line 335 "CSSPropertyNames.gperf"
    {"-webkit-transition-delay", CSSPropertyWebkitTransitionDelay},
#line 251 "CSSPropertyNames.gperf"
    {"-webkit-flex-wrap", CSSPropertyWebkitFlexWrap},
#line 118 "CSSPropertyNames.gperf"
    {"max-height", CSSPropertyMaxHeight},
#line 209 "CSSPropertyNames.gperf"
    {"-webkit-border-end-style", CSSPropertyWebkitBorderEndStyle},
#line 386 "CSSPropertyNames.gperf"
    {"baseline-shift", CSSPropertyBaselineShift},
#line 201 "CSSPropertyNames.gperf"
    {"-webkit-border-after-style", CSSPropertyWebkitBorderAfterStyle},
#line 205 "CSSPropertyNames.gperf"
    {"-webkit-border-before-style", CSSPropertyWebkitBorderBeforeStyle},
#line 161 "CSSPropertyNames.gperf"
    {"text-overline-mode", CSSPropertyTextOverlineMode},
#line 311 "CSSPropertyNames.gperf"
    {"-webkit-perspective", CSSPropertyWebkitPerspective},
#line 227 "CSSPropertyNames.gperf"
    {"-webkit-box-pack", CSSPropertyWebkitBoxPack},
#line 175 "CSSPropertyNames.gperf"
    {"visibility", CSSPropertyVisibility},
#line 216 "CSSPropertyNames.gperf"
    {"-webkit-border-start-color", CSSPropertyWebkitBorderStartColor},
#line 286 "CSSPropertyNames.gperf"
    {"-webkit-mask-box-image-repeat", CSSPropertyWebkitMaskBoxImageRepeat},
#line 224 "CSSPropertyNames.gperf"
    {"-webkit-box-lines", CSSPropertyWebkitBoxLines},
#line 296 "CSSPropertyNames.gperf"
    {"-webkit-mask-position-y", CSSPropertyWebkitMaskPositionY},
#line 69 "CSSPropertyNames.gperf"
    {"border-image-outset", CSSPropertyBorderImageOutset},
#line 124 "CSSPropertyNames.gperf"
    {"outline", CSSPropertyOutline},
#line 378 "CSSPropertyNames.gperf"
    {"stroke-dasharray", CSSPropertyStrokeDasharray},
#line 253 "CSSPropertyNames.gperf"
    {"-webkit-highlight", CSSPropertyWebkitHighlight},
#line 385 "CSSPropertyNames.gperf"
    {"alignment-baseline", CSSPropertyAlignmentBaseline},
#line 64 "CSSPropertyNames.gperf"
    {"border-bottom-style", CSSPropertyBorderBottomStyle},
#line 80 "CSSPropertyNames.gperf"
    {"border-right-color", CSSPropertyBorderRightColor},
#line 289 "CSSPropertyNames.gperf"
    {"-webkit-mask-box-image-width", CSSPropertyWebkitMaskBoxImageWidth},
#line 312 "CSSPropertyNames.gperf"
    {"-webkit-perspective-origin", CSSPropertyWebkitPerspectiveOrigin},
#line 391 "CSSPropertyNames.gperf"
    {"text-anchor", CSSPropertyTextAnchor},
#line 172 "CSSPropertyNames.gperf"
    {"unicode-bidi", CSSPropertyUnicodeBidi},
#line 28 "CSSPropertyNames.gperf"
    {"display", CSSPropertyDisplay},
#line 71 "CSSPropertyNames.gperf"
    {"border-image-slice", CSSPropertyBorderImageSlice},
#line 40 "CSSPropertyNames.gperf"
    {"-webkit-locale", CSSPropertyWebkitLocale},
#line 291 "CSSPropertyNames.gperf"
    {"-webkit-mask-composite", CSSPropertyWebkitMaskComposite},
#line 295 "CSSPropertyNames.gperf"
    {"-webkit-mask-position-x", CSSPropertyWebkitMaskPositionX},
#line 89 "CSSPropertyNames.gperf"
    {"border-top-style", CSSPropertyBorderTopStyle},
#line 363 "CSSPropertyNames.gperf"
    {"stop-color", CSSPropertyStopColor},
#line 360 "CSSPropertyNames.gperf"
    {"flood-color", CSSPropertyFloodColor},
#line 163 "CSSPropertyNames.gperf"
    {"text-overline-width", CSSPropertyTextOverlineWidth},
#line 380 "CSSPropertyNames.gperf"
    {"stroke-linecap", CSSPropertyStrokeLinecap},
#line 46 "CSSPropertyNames.gperf"
    {"background", CSSPropertyBackground},
#line 280 "CSSPropertyNames.gperf"
    {"-webkit-marquee-speed", CSSPropertyWebkitMarqueeSpeed},
#line 173 "CSSPropertyNames.gperf"
    {"unicode-range", CSSPropertyUnicodeRange},
#line 75 "CSSPropertyNames.gperf"
    {"border-left-color", CSSPropertyBorderLeftColor},
#line 383 "CSSPropertyNames.gperf"
    {"stroke-opacity", CSSPropertyStrokeOpacity},
#line 258 "CSSPropertyNames.gperf"
    {"-webkit-hyphens", CSSPropertyWebkitHyphens},
#line 108 "CSSPropertyNames.gperf"
    {"letter-spacing", CSSPropertyLetterSpacing},
#line 246 "CSSPropertyNames.gperf"
    {"-webkit-flex-flow", CSSPropertyWebkitFlexFlow},
#line 290 "CSSPropertyNames.gperf"
    {"-webkit-mask-clip", CSSPropertyWebkitMaskClip},
#line 36 "CSSPropertyNames.gperf"
    {"-webkit-font-feature-settings", CSSPropertyWebkitFontFeatureSettings},
#line 217 "CSSPropertyNames.gperf"
    {"-webkit-border-start-style", CSSPropertyWebkitBorderStartStyle},
#line 190 "CSSPropertyNames.gperf"
    {"-webkit-animation-play-state", CSSPropertyWebkitAnimationPlayState},
#line 277 "CSSPropertyNames.gperf"
    {"-webkit-marquee-direction", CSSPropertyWebkitMarqueeDirection},
#line 51 "CSSPropertyNames.gperf"
    {"background-origin", CSSPropertyBackgroundOrigin},
#line 197 "CSSPropertyNames.gperf"
    {"-webkit-background-origin", CSSPropertyWebkitBackgroundOrigin},
#line 244 "CSSPropertyNames.gperf"
    {"-webkit-flex-align", CSSPropertyWebkitFlexAlign},
#line 188 "CSSPropertyNames.gperf"
    {"-webkit-animation-iteration-count", CSSPropertyWebkitAnimationIterationCount},
#line 81 "CSSPropertyNames.gperf"
    {"border-right-style", CSSPropertyBorderRightStyle},
#line 228 "CSSPropertyNames.gperf"
    {"-webkit-box-reflect", CSSPropertyWebkitBoxReflect},
#line 245 "CSSPropertyNames.gperf"
    {"-webkit-flex-direction", CSSPropertyWebkitFlexDirection},
#line 174 "CSSPropertyNames.gperf"
    {"vertical-align", CSSPropertyVerticalAlign},
#line 259 "CSSPropertyNames.gperf"
    {"-webkit-line-box-contain", CSSPropertyWebkitLineBoxContain},
#line 50 "CSSPropertyNames.gperf"
    {"background-image", CSSPropertyBackgroundImage},
#line 128 "CSSPropertyNames.gperf"
    {"outline-width", CSSPropertyOutlineWidth},
#line 333 "CSSPropertyNames.gperf"
    {"-webkit-transform-style", CSSPropertyWebkitTransformStyle},
#line 355 "CSSPropertyNames.gperf"
    {"clip-path", CSSPropertyClipPath},
#line 126 "CSSPropertyNames.gperf"
    {"outline-offset", CSSPropertyOutlineOffset},
#line 63 "CSSPropertyNames.gperf"
    {"border-bottom-right-radius", CSSPropertyBorderBottomRightRadius},
#line 278 "CSSPropertyNames.gperf"
    {"-webkit-marquee-increment", CSSPropertyWebkitMarqueeIncrement},
#line 398 "CSSPropertyNames.gperf"
    {"-webkit-border-bottom-right-radius", CSSPropertyBorderBottomRightRadius},
#line 222 "CSSPropertyNames.gperf"
    {"-webkit-box-flex", CSSPropertyWebkitBoxFlex},
#line 247 "CSSPropertyNames.gperf"
    {"-webkit-flex-item-align", CSSPropertyWebkitFlexItemAlign},
#line 367 "CSSPropertyNames.gperf"
    {"color-profile", CSSPropertyColorProfile},
#line 364 "CSSPropertyNames.gperf"
    {"stop-opacity", CSSPropertyStopOpacity},
#line 361 "CSSPropertyNames.gperf"
    {"flood-opacity", CSSPropertyFloodOpacity},
#line 101 "CSSPropertyNames.gperf"
    {"cursor", CSSPropertyCursor},
#line 191 "CSSPropertyNames.gperf"
    {"-webkit-animation-timing-function", CSSPropertyWebkitAnimationTimingFunction},
#line 319 "CSSPropertyNames.gperf"
    {"-webkit-text-emphasis", CSSPropertyWebkitTextEmphasis},
#line 55 "CSSPropertyNames.gperf"
    {"background-repeat", CSSPropertyBackgroundRepeat},
#line 365 "CSSPropertyNames.gperf"
    {"color-interpolation", CSSPropertyColorInterpolation},
#line 353 "CSSPropertyNames.gperf"
    {"-webkit-wrap-through", CSSPropertyWebkitWrapThrough},
#line 100 "CSSPropertyNames.gperf"
    {"counter-reset", CSSPropertyCounterReset},
#line 76 "CSSPropertyNames.gperf"
    {"border-left-style", CSSPropertyBorderLeftStyle},
#line 262 "CSSPropertyNames.gperf"
    {"-webkit-line-clamp", CSSPropertyWebkitLineClamp},
#line 395 "CSSPropertyNames.gperf"
    {"-epub-text-orientation", CSSPropertyWebkitTextOrientation},
#line 88 "CSSPropertyNames.gperf"
    {"border-top-right-radius", CSSPropertyBorderTopRightRadius},
#line 400 "CSSPropertyNames.gperf"
    {"-webkit-border-top-right-radius", CSSPropertyBorderTopRightRadius},
#line 265 "CSSPropertyNames.gperf"
    {"-webkit-logical-width", CSSPropertyWebkitLogicalWidth},
#line 340 "CSSPropertyNames.gperf"
    {"-webkit-user-modify", CSSPropertyWebkitUserModify},
#line 250 "CSSPropertyNames.gperf"
    {"-webkit-flex-pack", CSSPropertyWebkitFlexPack},
#line 62 "CSSPropertyNames.gperf"
    {"border-bottom-left-radius", CSSPropertyBorderBottomLeftRadius},
#line 397 "CSSPropertyNames.gperf"
    {"-webkit-border-bottom-left-radius", CSSPropertyBorderBottomLeftRadius},
#line 58 "CSSPropertyNames.gperf"
    {"background-size", CSSPropertyBackgroundSize},
#line 255 "CSSPropertyNames.gperf"
    {"-webkit-hyphenate-limit-after", CSSPropertyWebkitHyphenateLimitAfter},
#line 198 "CSSPropertyNames.gperf"
    {"-webkit-background-size", CSSPropertyWebkitBackgroundSize},
#line 256 "CSSPropertyNames.gperf"
    {"-webkit-hyphenate-limit-before", CSSPropertyWebkitHyphenateLimitBefore},
#line 362 "CSSPropertyNames.gperf"
    {"lighting-color", CSSPropertyLightingColor},
#line 39 "CSSPropertyNames.gperf"
    {"-webkit-font-variant-ligatures", CSSPropertyWebkitFontVariantLigatures},
#line 304 "CSSPropertyNames.gperf"
    {"-webkit-min-logical-width", CSSPropertyWebkitMinLogicalWidth},
#line 72 "CSSPropertyNames.gperf"
    {"border-image-source", CSSPropertyBorderImageSource},
#line 87 "CSSPropertyNames.gperf"
    {"border-top-left-radius", CSSPropertyBorderTopLeftRadius},
#line 399 "CSSPropertyNames.gperf"
    {"-webkit-border-top-left-radius", CSSPropertyBorderTopLeftRadius},
#line 338 "CSSPropertyNames.gperf"
    {"-webkit-transition-timing-function", CSSPropertyWebkitTransitionTimingFunction},
#line 314 "CSSPropertyNames.gperf"
    {"-webkit-perspective-origin-y", CSSPropertyWebkitPerspectiveOriginY},
#line 326 "CSSPropertyNames.gperf"
    {"-webkit-text-stroke-color", CSSPropertyWebkitTextStrokeColor},
#line 212 "CSSPropertyNames.gperf"
    {"-webkit-border-horizontal-spacing", CSSPropertyWebkitBorderHorizontalSpacing},
#line 109 "CSSPropertyNames.gperf"
    {"list-style", CSSPropertyListStyle},
#line 66 "CSSPropertyNames.gperf"
    {"border-collapse", CSSPropertyBorderCollapse},
#line 358 "CSSPropertyNames.gperf"
    {"enable-background", CSSPropertyEnableBackground},
#line 318 "CSSPropertyNames.gperf"
    {"-webkit-text-decorations-in-effect", CSSPropertyWebkitTextDecorationsInEffect},
#line 52 "CSSPropertyNames.gperf"
    {"background-position", CSSPropertyBackgroundPosition},
#line 166 "CSSPropertyNames.gperf"
    {"text-underline", CSSPropertyTextUnderline},
#line 313 "CSSPropertyNames.gperf"
    {"-webkit-perspective-origin-x", CSSPropertyWebkitPerspectiveOriginX},
#line 232 "CSSPropertyNames.gperf"
    {"-webkit-column-break-after", CSSPropertyWebkitColumnBreakAfter},
#line 233 "CSSPropertyNames.gperf"
    {"-webkit-column-break-before", CSSPropertyWebkitColumnBreakBefore},
#line 99 "CSSPropertyNames.gperf"
    {"counter-increment", CSSPropertyCounterIncrement},
#line 271 "CSSPropertyNames.gperf"
    {"-webkit-margin-collapse", CSSPropertyWebkitMarginCollapse},
#line 168 "CSSPropertyNames.gperf"
    {"text-underline-mode", CSSPropertyTextUnderlineMode},
#line 266 "CSSPropertyNames.gperf"
    {"-webkit-logical-height", CSSPropertyWebkitLogicalHeight},
#line 230 "CSSPropertyNames.gperf"
    {"-webkit-color-correction", CSSPropertyWebkitColorCorrection},
#line 402 "CSSPropertyNames.gperf"
    {"-epub-caption-side", CSSPropertyCaptionSide},
#line 110 "CSSPropertyNames.gperf"
    {"list-style-image", CSSPropertyListStyleImage},
#line 404 "CSSPropertyNames.gperf"
    {"-epub-text-transform", CSSPropertyTextTransform},
#line 42 "CSSPropertyNames.gperf"
    {"-webkit-text-size-adjust", CSSPropertyWebkitTextSizeAdjust},
#line 267 "CSSPropertyNames.gperf"
    {"-webkit-margin-after-collapse", CSSPropertyWebkitMarginAfterCollapse},
#line 268 "CSSPropertyNames.gperf"
    {"-webkit-margin-before-collapse", CSSPropertyWebkitMarginBeforeCollapse},
#line 346 "CSSPropertyNames.gperf"
    {"-webkit-wrap-shape-outside", CSSPropertyWebkitWrapShapeOutside},
#line 370 "CSSPropertyNames.gperf"
    {"fill-opacity", CSSPropertyFillOpacity},
#line 305 "CSSPropertyNames.gperf"
    {"-webkit-min-logical-height", CSSPropertyWebkitMinLogicalHeight},
#line 269 "CSSPropertyNames.gperf"
    {"-webkit-margin-bottom-collapse", CSSPropertyWebkitMarginBottomCollapse},
#line 219 "CSSPropertyNames.gperf"
    {"-webkit-border-vertical-spacing", CSSPropertyWebkitBorderVerticalSpacing},
#line 321 "CSSPropertyNames.gperf"
    {"-webkit-text-emphasis-position", CSSPropertyWebkitTextEmphasisPosition},
#line 57 "CSSPropertyNames.gperf"
    {"background-repeat-y", CSSPropertyBackgroundRepeatY},
#line 160 "CSSPropertyNames.gperf"
    {"text-overline-color", CSSPropertyTextOverlineColor},
#line 236 "CSSPropertyNames.gperf"
    {"-webkit-column-gap", CSSPropertyWebkitColumnGap},
#line 243 "CSSPropertyNames.gperf"
    {"-webkit-columns", CSSPropertyWebkitColumns},
#line 242 "CSSPropertyNames.gperf"
    {"-webkit-column-width", CSSPropertyWebkitColumnWidth},
#line 281 "CSSPropertyNames.gperf"
    {"-webkit-marquee-style", CSSPropertyWebkitMarqueeStyle},
#line 248 "CSSPropertyNames.gperf"
    {"-webkit-flex-line-pack", CSSPropertyWebkitFlexLinePack},
#line 170 "CSSPropertyNames.gperf"
    {"text-underline-width", CSSPropertyTextUnderlineWidth},
#line 225 "CSSPropertyNames.gperf"
    {"-webkit-box-ordinal-group", CSSPropertyWebkitBoxOrdinalGroup},
#line 234 "CSSPropertyNames.gperf"
    {"-webkit-column-break-inside", CSSPropertyWebkitColumnBreakInside},
#line 371 "CSSPropertyNames.gperf"
    {"fill-rule", CSSPropertyFillRule},
#line 285 "CSSPropertyNames.gperf"
    {"-webkit-mask-box-image-outset", CSSPropertyWebkitMaskBoxImageOutset},
#line 270 "CSSPropertyNames.gperf"
    {"-webkit-margin-top-collapse", CSSPropertyWebkitMarginTopCollapse},
#line 56 "CSSPropertyNames.gperf"
    {"background-repeat-x", CSSPropertyBackgroundRepeatX},
#line 407 "CSSPropertyNames.gperf"
    {"-epub-text-combine", CSSPropertyWebkitTextCombine},
#line 149 "CSSPropertyNames.gperf"
    {"table-layout", CSSPropertyTableLayout},
#line 287 "CSSPropertyNames.gperf"
    {"-webkit-mask-box-image-slice", CSSPropertyWebkitMaskBoxImageSlice},
#line 388 "CSSPropertyNames.gperf"
    {"glyph-orientation-horizontal", CSSPropertyGlyphOrientationHorizontal},
#line 125 "CSSPropertyNames.gperf"
    {"outline-color", CSSPropertyOutlineColor},
#line 194 "CSSPropertyNames.gperf"
    {"-webkit-backface-visibility", CSSPropertyWebkitBackfaceVisibility},
#line 47 "CSSPropertyNames.gperf"
    {"background-attachment", CSSPropertyBackgroundAttachment},
#line 315 "CSSPropertyNames.gperf"
    {"-webkit-print-color-adjust", CSSPropertyWebkitPrintColorAdjust},
#line 341 "CSSPropertyNames.gperf"
    {"-webkit-user-select", CSSPropertyWebkitUserSelect},
#line 162 "CSSPropertyNames.gperf"
    {"text-overline-style", CSSPropertyTextOverlineStyle},
#line 111 "CSSPropertyNames.gperf"
    {"list-style-position", CSSPropertyListStylePosition},
#line 241 "CSSPropertyNames.gperf"
    {"-webkit-column-span", CSSPropertyWebkitColumnSpan},
#line 302 "CSSPropertyNames.gperf"
    {"-webkit-max-logical-width", CSSPropertyWebkitMaxLogicalWidth},
#line 366 "CSSPropertyNames.gperf"
    {"color-interpolation-filters", CSSPropertyColorInterpolationFilters},
#line 54 "CSSPropertyNames.gperf"
    {"background-position-y", CSSPropertyBackgroundPositionY},
#line 102 "CSSPropertyNames.gperf"
    {"empty-cells", CSSPropertyEmptyCells},
#line 49 "CSSPropertyNames.gperf"
    {"background-color", CSSPropertyBackgroundColor},
#line 323 "CSSPropertyNames.gperf"
    {"-webkit-text-fill-color", CSSPropertyWebkitTextFillColor},
#line 356 "CSSPropertyNames.gperf"
    {"clip-rule", CSSPropertyClipRule},
#line 257 "CSSPropertyNames.gperf"
    {"-webkit-hyphenate-limit-lines", CSSPropertyWebkitHyphenateLimitLines},
#line 153 "CSSPropertyNames.gperf"
    {"text-line-through", CSSPropertyTextLineThrough},
#line 53 "CSSPropertyNames.gperf"
    {"background-position-x", CSSPropertyBackgroundPositionX},
#line 196 "CSSPropertyNames.gperf"
    {"-webkit-background-composite", CSSPropertyWebkitBackgroundComposite},
#line 127 "CSSPropertyNames.gperf"
    {"outline-style", CSSPropertyOutlineStyle},
#line 254 "CSSPropertyNames.gperf"
    {"-webkit-hyphenate-character", CSSPropertyWebkitHyphenateCharacter},
#line 406 "CSSPropertyNames.gperf"
    {"-epub-hyphens", CSSPropertyWebkitHyphens},
#line 389 "CSSPropertyNames.gperf"
    {"glyph-orientation-vertical", CSSPropertyGlyphOrientationVertical},
#line 112 "CSSPropertyNames.gperf"
    {"list-style-type", CSSPropertyListStyleType},
#line 48 "CSSPropertyNames.gperf"
    {"background-clip", CSSPropertyBackgroundClip},
#line 195 "CSSPropertyNames.gperf"
    {"-webkit-background-clip", CSSPropertyWebkitBackgroundClip},
#line 155 "CSSPropertyNames.gperf"
    {"text-line-through-mode", CSSPropertyTextLineThroughMode},
#line 320 "CSSPropertyNames.gperf"
    {"-webkit-text-emphasis-color", CSSPropertyWebkitTextEmphasisColor},
#line 303 "CSSPropertyNames.gperf"
    {"-webkit-max-logical-height", CSSPropertyWebkitMaxLogicalHeight},
#line 324 "CSSPropertyNames.gperf"
    {"-webkit-text-security", CSSPropertyWebkitTextSecurity},
#line 408 "CSSPropertyNames.gperf"
    {"-epub-text-emphasis", CSSPropertyWebkitTextEmphasis},
#line 288 "CSSPropertyNames.gperf"
    {"-webkit-mask-box-image-source", CSSPropertyWebkitMaskBoxImageSource},
#line 223 "CSSPropertyNames.gperf"
    {"-webkit-box-flex-group", CSSPropertyWebkitBoxFlexGroup},
#line 231 "CSSPropertyNames.gperf"
    {"-webkit-column-axis", CSSPropertyWebkitColumnAxis},
#line 157 "CSSPropertyNames.gperf"
    {"text-line-through-width", CSSPropertyTextLineThroughWidth},
#line 322 "CSSPropertyNames.gperf"
    {"-webkit-text-emphasis-style", CSSPropertyWebkitTextEmphasisStyle},
#line 167 "CSSPropertyNames.gperf"
    {"text-underline-color", CSSPropertyTextUnderlineColor},
#line 169 "CSSPropertyNames.gperf"
    {"text-underline-style", CSSPropertyTextUnderlineStyle},
#line 237 "CSSPropertyNames.gperf"
    {"-webkit-column-rule", CSSPropertyWebkitColumnRule},
#line 235 "CSSPropertyNames.gperf"
    {"-webkit-column-count", CSSPropertyWebkitColumnCount},
#line 154 "CSSPropertyNames.gperf"
    {"text-line-through-color", CSSPropertyTextLineThroughColor},
#line 240 "CSSPropertyNames.gperf"
    {"-webkit-column-rule-width", CSSPropertyWebkitColumnRuleWidth},
#line 409 "CSSPropertyNames.gperf"
    {"-epub-text-emphasis-color", CSSPropertyWebkitTextEmphasisColor},
#line 156 "CSSPropertyNames.gperf"
    {"text-line-through-style", CSSPropertyTextLineThroughStyle},
#line 410 "CSSPropertyNames.gperf"
    {"-epub-text-emphasis-style", CSSPropertyWebkitTextEmphasisStyle},
#line 238 "CSSPropertyNames.gperf"
    {"-webkit-column-rule-color", CSSPropertyWebkitColumnRuleColor},
#line 239 "CSSPropertyNames.gperf"
    {"-webkit-column-rule-style", CSSPropertyWebkitColumnRuleStyle},
#line 301 "CSSPropertyNames.gperf"
    {"-webkit-match-nearest-mail-blockquote-color", CSSPropertyWebkitMatchNearestMailBlockquoteColor}
  };

static const short lookup[] =
  {
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,   0,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,   1,  -1,  -1,  -1,  -1,
      2,   3,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,   4,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,   5,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,   6,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,   7,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,   8,  -1,  -1,  -1,  -1,
     -1,   9,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  10,  -1,  -1,  -1,  -1,
     11,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     12,  13,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     14,  15,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  16,  -1,  -1,  -1,
     17,  -1,  -1,  -1,  -1,  18,  -1,  -1,  -1,  -1,
     19,  -1,  -1,  -1,  -1,  20,  -1,  -1,  -1,  -1,
     21,  -1,  -1,  -1,  -1,  22,  -1,  -1,  -1,  -1,
     23,  24,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  25,  -1,  -1,  -1,  26,  -1,  -1,  -1,  -1,
     27,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     28,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  29,  -1,  -1,  -1,  -1,
     30,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     31,  -1,  -1,  -1,  -1,  32,  -1,  -1,  -1,  -1,
     33,  -1,  -1,  -1,  -1,  34,  -1,  -1,  -1,  -1,
     -1,  35,  -1,  -1,  -1,  36,  -1,  -1,  -1,  -1,
     37,  -1,  -1,  -1,  -1,  38,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  39,  -1,  -1,  -1,
     40,  -1,  -1,  -1,  -1,  -1,  41,  -1,  -1,  -1,
     -1,  42,  -1,  -1,  -1,  -1,  43,  -1,  -1,  -1,
     -1,  44,  -1,  -1,  -1,  45,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  46,  -1,  -1,  -1,
     47,  48,  -1,  -1,  -1,  49,  -1,  50,  -1,  -1,
     -1,  -1,  51,  -1,  -1,  -1,  -1,  52,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  53,  54,  -1,  -1,  -1,
     55,  -1,  -1,  -1,  -1,  56,  57,  -1,  -1,  -1,
     58,  -1,  -1,  -1,  -1,  59,  60,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     61,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     62,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  63,  64,  -1,  -1,  -1,
     65,  66,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  67,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  68,  69,  -1,  -1,  -1,
     -1,  70,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     71,  72,  -1,  -1,  -1,  73,  74,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  75,  -1,  -1,  -1,  -1,
     -1,  76,  -1,  -1,  -1,  77,  78,  -1,  -1,  -1,
     79,  80,  -1,  -1,  -1,  -1,  81,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  82,  -1,  -1,  -1,  -1,
     -1,  83,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  84,  -1,  -1,  -1,  -1,
     85,  -1,  -1,  -1,  -1,  86,  -1,  -1,  -1,  -1,
     87,  -1,  -1,  -1,  -1,  -1,  88,  -1,  -1,  -1,
     89,  90,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  91,  -1,  -1,  -1,  -1,
     92,  -1,  93,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     94,  -1,  95,  -1,  -1,  -1,  96,  -1,  -1,  -1,
     -1,  97,  -1,  -1,  -1,  -1,  98,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  99,  -1,  -1,  -1,
     -1, 100,  -1,  -1,  -1, 101,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1, 102,  -1,  -1,
     -1, 103,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1, 104,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1, 105,  -1,  -1,  -1, 106,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1, 107, 108,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1, 109,  -1,  -1,  -1,
    110,  -1,  -1,  -1,  -1,  -1, 111,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1, 112, 113,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1, 114, 115,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    116,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    117,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1, 118,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1, 119,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    120,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    121,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1, 122,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1, 123,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1, 124,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1, 125,  -1, 126,  -1,  -1,
    127,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1, 128,  -1,  -1,  -1,
     -1,  -1, 129,  -1,  -1, 130,  -1,  -1,  -1,  -1,
    131, 132,  -1,  -1,  -1, 133, 134,  -1,  -1,  -1,
    135,  -1, 136,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    137,  -1,  -1,  -1,  -1, 138,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    139,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    140,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    141,  -1, 142, 143,  -1, 144,  -1,  -1,  -1,  -1,
     -1, 145,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1, 146,  -1,  -1,  -1, 147, 148, 149,  -1,  -1,
     -1, 150, 151,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1, 152,  -1,  -1,  -1,  -1, 153,  -1,  -1,
    154,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1, 155,  -1, 156,  -1,  -1, 157,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1, 158,  -1,  -1,  -1,
    159,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1, 160,  -1,  -1,  -1, 161,  -1, 162,  -1,  -1,
     -1,  -1, 163,  -1,  -1,  -1, 164, 165,  -1,  -1,
     -1, 166,  -1,  -1,  -1, 167,  -1, 168,  -1,  -1,
     -1,  -1, 169,  -1,  -1, 170,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1, 171,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1, 172,  -1,  -1,  -1,  -1, 173,  -1,  -1,
     -1, 174,  -1,  -1,  -1, 175,  -1,  -1,  -1,  -1,
    176, 177,  -1,  -1,  -1,  -1, 178,  -1,  -1,  -1,
     -1, 179,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1, 180,  -1, 181,  -1,  -1,
    182, 183,  -1,  -1,  -1, 184, 185,  -1,  -1,  -1,
    186, 187,  -1,  -1,  -1,  -1, 188,  -1,  -1,  -1,
    189, 190,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1, 191, 192, 193,  -1,
     -1, 194, 195,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1, 196,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1, 197,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1, 198,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    199,  -1,  -1,  -1,  -1,  -1, 200,  -1,  -1,  -1,
     -1, 201,  -1,  -1,  -1, 202,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1, 203,  -1,  -1,  -1,
     -1, 204,  -1,  -1,  -1,  -1, 205,  -1,  -1,  -1,
    206,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    207,  -1, 208, 209,  -1, 210, 211,  -1,  -1,  -1,
     -1, 212,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1, 213,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    214,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1, 215,  -1,  -1,
    216, 217,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    218,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    219,  -1,  -1,  -1,  -1, 220, 221,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1, 222,  -1,  -1,  -1,
    223, 224, 225,  -1,  -1, 226,  -1,  -1,  -1,  -1,
    227,  -1,  -1,  -1,  -1, 228,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    229, 230,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1, 231,  -1, 232,  -1,  -1,  -1,  -1,  -1,  -1,
    233,  -1,  -1,  -1,  -1,  -1,  -1,  -1, 234,  -1,
    235,  -1,  -1,  -1,  -1,  -1,  -1, 236,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1, 237,  -1,  -1,  -1,
     -1, 238,  -1,  -1,  -1, 239,  -1,  -1,  -1,  -1,
    240,  -1,  -1,  -1,  -1, 241,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1, 242,  -1,  -1,
    243,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1, 244,  -1,  -1,  -1,  -1, 245,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1, 246,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    247, 248,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    249, 250, 251,  -1,  -1,  -1, 252,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1, 253,  -1,  -1,
     -1, 254,  -1,  -1,  -1, 255, 256,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1, 257,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1, 258,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1, 259,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1, 260, 261,  -1,  -1,
     -1,  -1,  -1,  -1,  -1, 262, 263, 264,  -1,  -1,
     -1,  -1,  -1,  -1,  -1, 265,  -1,  -1,  -1,  -1,
    266,  -1, 267,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    268,  -1, 269,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    270,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1, 271,  -1,  -1,  -1,
     -1, 272,  -1,  -1,  -1,  -1, 273,  -1,  -1,  -1,
     -1, 274,  -1,  -1,  -1,  -1,  -1, 275,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1, 276,  -1,  -1,
     -1, 277,  -1,  -1,  -1,  -1, 278,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1, 279,  -1,  -1,  -1, 280,
    281,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1, 282,
     -1, 283,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1, 284,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1, 285,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    286, 287,  -1,  -1,  -1,  -1, 288,  -1,  -1,  -1,
     -1, 289,  -1,  -1,  -1,  -1, 290,  -1,  -1,  -1,
     -1, 291,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1, 292,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1, 293,  -1,  -1,  -1, 294,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    295,  -1,  -1, 296,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1, 297,  -1,  -1,  -1,  -1,
     -1, 298,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1, 299,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1, 300,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1, 301,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    302,  -1,  -1,  -1,  -1, 303,  -1,  -1,  -1,  -1,
     -1, 304, 305,  -1,  -1, 306,  -1,  -1,  -1,  -1,
    307, 308, 309,  -1,  -1,  -1, 310,  -1,  -1,  -1,
     -1, 311,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1, 312,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1, 313, 314,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1, 315,  -1,  -1,
    316,  -1,  -1,  -1,  -1, 317,  -1,  -1,  -1,  -1,
     -1,  -1, 318,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1, 319,  -1,  -1,  -1,  -1, 320,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1, 321,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    322, 323,  -1,  -1,  -1,  -1, 324,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1, 325,  -1,  -1,
     -1,  -1, 326,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1, 327,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    328,  -1,  -1,  -1,  -1,  -1, 329,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1, 330,  -1,  -1,  -1,
    331,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1, 332,  -1,  -1,  -1,  -1, 333,  -1,  -1,  -1,
     -1, 334,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1, 335,  -1,  -1,  -1,
     -1,  -1,  -1, 336,  -1, 337,  -1,  -1,  -1,  -1,
     -1,  -1, 338,  -1,  -1,  -1, 339,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1, 340,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1, 341,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1, 342,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1, 343,  -1,  -1,  -1,
    344,  -1,  -1,  -1,  -1,  -1,  -1, 345,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1, 346,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1, 347,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1, 348,  -1,  -1,  -1, 349,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1, 350,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    351,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1, 352,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1, 353,  -1,  -1,  -1,  -1,  -1,  -1,
     -1, 354,  -1,  -1,  -1, 355,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1, 356,  -1,  -1, 357,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1, 358,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1, 359,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1, 360,  -1,  -1,
     -1,  -1,  -1,  -1,  -1, 361,  -1,  -1,  -1,  -1,
    362,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1, 363,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1, 364,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1, 365,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1, 366,  -1,  -1,
     -1,  -1, 367,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1, 368,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1, 369,  -1,  -1,  -1,  -1,  -1,  -1,
     -1, 370,  -1,  -1, 371,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1, 372,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1, 373,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1, 374,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1, 375,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1, 376,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1, 377,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1, 378,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1, 379,  -1, 380,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1, 381,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
    382,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1, 383,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
     -1,  -1,  -1,  -1,  -1,  -1, 384
  };

const struct Property *
CSSPropertyNamesHash::findPropertyImpl (register const char *str, register unsigned int len)
{
  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH)
    {
      register int key = propery_hash_function (str, len);

      if (key <= MAX_HASH_VALUE && key >= 0)
        {
          register int index = lookup[key];

          if (index >= 0)
            {
              register const char *s = property_wordlist[index].name;

              if (*str == *s && !strncmp (str + 1, s + 1, len - 1) && s[len] == '\0')
                return &property_wordlist[index];
            }
        }
    }
  return 0;
}
#line 411 "CSSPropertyNames.gperf"

const Property* findProperty(register const char* str, register unsigned int len)
{
    return CSSPropertyNamesHash::findPropertyImpl(str, len);
}

const char* getPropertyName(CSSPropertyID id)
{
    if (id < firstCSSProperty)
        return 0;
    int index = id - firstCSSProperty;
    if (index >= numCSSProperties)
        return 0;
    return propertyNameStrings[index];
}

WTF::String getJSPropertyName(CSSPropertyID id)
{
    char result[maxCSSPropertyNameLength + 1];
    const char* cssPropertyName = getPropertyName(id);
    const char* propertyNamePointer = cssPropertyName;
    if (!propertyNamePointer)
        return emptyString();

    char* resultPointer = result;
    while (char character = *propertyNamePointer++) {
        if (character == '-') {
            char nextCharacter = *propertyNamePointer++;
            if (!nextCharacter)
                break;
            character = (propertyNamePointer - 2 != cssPropertyName) ? toASCIIUpper(nextCharacter) : nextCharacter;
        }
        *resultPointer++ = character;
    }
    *resultPointer = '\0';
    return WTF::String(result);
}

} // namespace WebCore
