/*
    This file is part of the WebKit open source project.
    This file has been generated by generate-bindings.pl. DO NOT MODIFY!

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB.  If not, write to
    the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
    Boston, MA 02110-1301, USA.
*/

#ifndef JSPeerConnection00_h
#define JSPeerConnection00_h

#if ENABLE(MEDIA_STREAM)

#include "JSDOMBinding.h"
#include "PeerConnection00.h"
#include <runtime/JSGlobalObject.h>
#include <runtime/JSObject.h>
#include <runtime/ObjectPrototype.h>

namespace WebCore {

class JSPeerConnection00 : public JSDOMWrapper {
public:
    typedef JSDOMWrapper Base;
    static JSPeerConnection00* create(JSC::Structure* structure, JSDOMGlobalObject* globalObject, PassRefPtr<PeerConnection00> impl)
    {
        JSPeerConnection00* ptr = new (NotNull, JSC::allocateCell<JSPeerConnection00>(globalObject->globalData().heap)) JSPeerConnection00(structure, globalObject, impl);
        ptr->finishCreation(globalObject->globalData());
        return ptr;
    }

    static JSC::JSObject* createPrototype(JSC::ExecState*, JSC::JSGlobalObject*);
    static bool getOwnPropertySlot(JSC::JSCell*, JSC::ExecState*, const JSC::Identifier& propertyName, JSC::PropertySlot&);
    static bool getOwnPropertyDescriptor(JSC::JSObject*, JSC::ExecState*, const JSC::Identifier& propertyName, JSC::PropertyDescriptor&);
    static void put(JSC::JSCell*, JSC::ExecState*, const JSC::Identifier& propertyName, JSC::JSValue, JSC::PutPropertySlot&);
    static void destroy(JSC::JSCell*);
    ~JSPeerConnection00();
    static const JSC::ClassInfo s_info;

    static JSC::Structure* createStructure(JSC::JSGlobalData& globalData, JSC::JSGlobalObject* globalObject, JSC::JSValue prototype)
    {
        return JSC::Structure::create(globalData, globalObject, prototype, JSC::TypeInfo(JSC::ObjectType, StructureFlags), &s_info);
    }

    static JSC::JSValue getConstructor(JSC::ExecState*, JSC::JSGlobalObject*);
    static void visitChildren(JSCell*, JSC::SlotVisitor&);

    PeerConnection00* impl() const { return m_impl; }
    void releaseImpl() { m_impl->deref(); m_impl = 0; }

    void releaseImplIfNotNull() { if (m_impl) { m_impl->deref(); m_impl = 0; } }

private:
    PeerConnection00* m_impl;
protected:
    JSPeerConnection00(JSC::Structure*, JSDOMGlobalObject*, PassRefPtr<PeerConnection00>);
    void finishCreation(JSC::JSGlobalData&);
    static const unsigned StructureFlags = JSC::OverridesGetOwnPropertySlot | JSC::OverridesVisitChildren | Base::StructureFlags;
};

class JSPeerConnection00Owner : public JSC::WeakHandleOwner {
    virtual bool isReachableFromOpaqueRoots(JSC::Handle<JSC::Unknown>, void* context, JSC::SlotVisitor&);
    virtual void finalize(JSC::Handle<JSC::Unknown>, void* context);
};

inline JSC::WeakHandleOwner* wrapperOwner(DOMWrapperWorld*, PeerConnection00*)
{
    DEFINE_STATIC_LOCAL(JSPeerConnection00Owner, jsPeerConnection00Owner, ());
    return &jsPeerConnection00Owner;
}

inline void* wrapperContext(DOMWrapperWorld* world, PeerConnection00*)
{
    return world;
}

JSC::JSValue toJS(JSC::ExecState*, JSDOMGlobalObject*, PeerConnection00*);
PeerConnection00* toPeerConnection00(JSC::JSValue);

class JSPeerConnection00Prototype : public JSC::JSNonFinalObject {
public:
    typedef JSC::JSNonFinalObject Base;
    static JSC::JSObject* self(JSC::ExecState*, JSC::JSGlobalObject*);
    static JSPeerConnection00Prototype* create(JSC::JSGlobalData& globalData, JSC::JSGlobalObject* globalObject, JSC::Structure* structure)
    {
        JSPeerConnection00Prototype* ptr = new (NotNull, JSC::allocateCell<JSPeerConnection00Prototype>(globalData.heap)) JSPeerConnection00Prototype(globalData, globalObject, structure);
        ptr->finishCreation(globalData);
        return ptr;
    }

    static const JSC::ClassInfo s_info;
    static bool getOwnPropertySlot(JSC::JSCell*, JSC::ExecState*, const JSC::Identifier&, JSC::PropertySlot&);
    static bool getOwnPropertyDescriptor(JSC::JSObject*, JSC::ExecState*, const JSC::Identifier&, JSC::PropertyDescriptor&);
    static JSC::Structure* createStructure(JSC::JSGlobalData& globalData, JSC::JSGlobalObject* globalObject, JSC::JSValue prototype)
    {
        return JSC::Structure::create(globalData, globalObject, prototype, JSC::TypeInfo(JSC::ObjectType, StructureFlags), &s_info);
    }

private:
    JSPeerConnection00Prototype(JSC::JSGlobalData& globalData, JSC::JSGlobalObject*, JSC::Structure* structure) : JSC::JSNonFinalObject(globalData, structure) { }
protected:
    static const unsigned StructureFlags = JSC::OverridesGetOwnPropertySlot | JSC::OverridesVisitChildren | Base::StructureFlags;
};

class JSPeerConnection00Constructor : public DOMConstructorObject {
private:
    JSPeerConnection00Constructor(JSC::Structure*, JSDOMGlobalObject*);
    void finishCreation(JSC::ExecState*, JSDOMGlobalObject*);

public:
    typedef DOMConstructorObject Base;
    static JSPeerConnection00Constructor* create(JSC::ExecState* exec, JSC::Structure* structure, JSDOMGlobalObject* globalObject)
    {
        JSPeerConnection00Constructor* ptr = new (NotNull, JSC::allocateCell<JSPeerConnection00Constructor>(*exec->heap())) JSPeerConnection00Constructor(structure, globalObject);
        ptr->finishCreation(exec, globalObject);
        return ptr;
    }

    static bool getOwnPropertySlot(JSC::JSCell*, JSC::ExecState*, const JSC::Identifier&, JSC::PropertySlot&);
    static bool getOwnPropertyDescriptor(JSC::JSObject*, JSC::ExecState*, const JSC::Identifier&, JSC::PropertyDescriptor&);
    static const JSC::ClassInfo s_info;
    static JSC::Structure* createStructure(JSC::JSGlobalData& globalData, JSC::JSGlobalObject* globalObject, JSC::JSValue prototype)
    {
        return JSC::Structure::create(globalData, globalObject, prototype, JSC::TypeInfo(JSC::ObjectType, StructureFlags), &s_info);
    }
protected:
    static const unsigned StructureFlags = JSC::OverridesGetOwnPropertySlot | JSC::ImplementsHasInstance | DOMConstructorObject::StructureFlags;
    static JSC::EncodedJSValue JSC_HOST_CALL constructJSPeerConnection00(JSC::ExecState*);
    static JSC::ConstructType getConstructData(JSC::JSCell*, JSC::ConstructData&);
};

// Functions

JSC::EncodedJSValue JSC_HOST_CALL jsPeerConnection00PrototypeFunctionCreateOffer(JSC::ExecState*);
JSC::EncodedJSValue JSC_HOST_CALL jsPeerConnection00PrototypeFunctionCreateAnswer(JSC::ExecState*);
JSC::EncodedJSValue JSC_HOST_CALL jsPeerConnection00PrototypeFunctionSetLocalDescription(JSC::ExecState*);
JSC::EncodedJSValue JSC_HOST_CALL jsPeerConnection00PrototypeFunctionSetRemoteDescription(JSC::ExecState*);
JSC::EncodedJSValue JSC_HOST_CALL jsPeerConnection00PrototypeFunctionStartIce(JSC::ExecState*);
JSC::EncodedJSValue JSC_HOST_CALL jsPeerConnection00PrototypeFunctionProcessIceMessage(JSC::ExecState*);
JSC::EncodedJSValue JSC_HOST_CALL jsPeerConnection00PrototypeFunctionAddStream(JSC::ExecState*);
JSC::EncodedJSValue JSC_HOST_CALL jsPeerConnection00PrototypeFunctionRemoveStream(JSC::ExecState*);
JSC::EncodedJSValue JSC_HOST_CALL jsPeerConnection00PrototypeFunctionClose(JSC::ExecState*);
JSC::EncodedJSValue JSC_HOST_CALL jsPeerConnection00PrototypeFunctionAddEventListener(JSC::ExecState*);
JSC::EncodedJSValue JSC_HOST_CALL jsPeerConnection00PrototypeFunctionRemoveEventListener(JSC::ExecState*);
JSC::EncodedJSValue JSC_HOST_CALL jsPeerConnection00PrototypeFunctionDispatchEvent(JSC::ExecState*);
// Attributes

JSC::JSValue jsPeerConnection00LocalDescription(JSC::ExecState*, JSC::JSValue, const JSC::Identifier&);
JSC::JSValue jsPeerConnection00RemoteDescription(JSC::ExecState*, JSC::JSValue, const JSC::Identifier&);
JSC::JSValue jsPeerConnection00ReadyState(JSC::ExecState*, JSC::JSValue, const JSC::Identifier&);
JSC::JSValue jsPeerConnection00IceState(JSC::ExecState*, JSC::JSValue, const JSC::Identifier&);
JSC::JSValue jsPeerConnection00LocalStreams(JSC::ExecState*, JSC::JSValue, const JSC::Identifier&);
JSC::JSValue jsPeerConnection00RemoteStreams(JSC::ExecState*, JSC::JSValue, const JSC::Identifier&);
JSC::JSValue jsPeerConnection00Onconnecting(JSC::ExecState*, JSC::JSValue, const JSC::Identifier&);
void setJSPeerConnection00Onconnecting(JSC::ExecState*, JSC::JSObject*, JSC::JSValue);
JSC::JSValue jsPeerConnection00Onopen(JSC::ExecState*, JSC::JSValue, const JSC::Identifier&);
void setJSPeerConnection00Onopen(JSC::ExecState*, JSC::JSObject*, JSC::JSValue);
JSC::JSValue jsPeerConnection00Onstatechange(JSC::ExecState*, JSC::JSValue, const JSC::Identifier&);
void setJSPeerConnection00Onstatechange(JSC::ExecState*, JSC::JSObject*, JSC::JSValue);
JSC::JSValue jsPeerConnection00Onaddstream(JSC::ExecState*, JSC::JSValue, const JSC::Identifier&);
void setJSPeerConnection00Onaddstream(JSC::ExecState*, JSC::JSObject*, JSC::JSValue);
JSC::JSValue jsPeerConnection00Onremovestream(JSC::ExecState*, JSC::JSValue, const JSC::Identifier&);
void setJSPeerConnection00Onremovestream(JSC::ExecState*, JSC::JSObject*, JSC::JSValue);
JSC::JSValue jsPeerConnection00Constructor(JSC::ExecState*, JSC::JSValue, const JSC::Identifier&);
// Constants

JSC::JSValue jsPeerConnection00SDP_OFFER(JSC::ExecState*, JSC::JSValue, const JSC::Identifier&);
JSC::JSValue jsPeerConnection00SDP_PRANSWER(JSC::ExecState*, JSC::JSValue, const JSC::Identifier&);
JSC::JSValue jsPeerConnection00SDP_ANSWER(JSC::ExecState*, JSC::JSValue, const JSC::Identifier&);
JSC::JSValue jsPeerConnection00NEW(JSC::ExecState*, JSC::JSValue, const JSC::Identifier&);
JSC::JSValue jsPeerConnection00NEGOTIATING(JSC::ExecState*, JSC::JSValue, const JSC::Identifier&);
JSC::JSValue jsPeerConnection00ACTIVE(JSC::ExecState*, JSC::JSValue, const JSC::Identifier&);
JSC::JSValue jsPeerConnection00CLOSED(JSC::ExecState*, JSC::JSValue, const JSC::Identifier&);
JSC::JSValue jsPeerConnection00ICE_GATHERING(JSC::ExecState*, JSC::JSValue, const JSC::Identifier&);
JSC::JSValue jsPeerConnection00ICE_WAITING(JSC::ExecState*, JSC::JSValue, const JSC::Identifier&);
JSC::JSValue jsPeerConnection00ICE_CHECKING(JSC::ExecState*, JSC::JSValue, const JSC::Identifier&);
JSC::JSValue jsPeerConnection00ICE_CONNECTED(JSC::ExecState*, JSC::JSValue, const JSC::Identifier&);
JSC::JSValue jsPeerConnection00ICE_COMPLETED(JSC::ExecState*, JSC::JSValue, const JSC::Identifier&);
JSC::JSValue jsPeerConnection00ICE_FAILED(JSC::ExecState*, JSC::JSValue, const JSC::Identifier&);
JSC::JSValue jsPeerConnection00ICE_CLOSED(JSC::ExecState*, JSC::JSValue, const JSC::Identifier&);

} // namespace WebCore

#endif // ENABLE(MEDIA_STREAM)

#endif
