/*
    This file is part of the WebKit open source project.
    This file has been generated by generate-bindings.pl. DO NOT MODIFY!

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Library General Public
    License as published by the Free Software Foundation; either
    version 2 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Library General Public License for more details.

    You should have received a copy of the GNU Library General Public License
    along with this library; see the file COPYING.LIB.  If not, write to
    the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
    Boston, MA 02110-1301, USA.
*/

#include "config.h"

#if ENABLE(INPUT_SPEECH)

#include "JSSpeechInputResultList.h"

#include "ExceptionCode.h"
#include "JSDOMBinding.h"
#include "JSSpeechInputResult.h"
#include "SpeechInputResult.h"
#include "SpeechInputResultList.h"
#include <runtime/Error.h>
#include <runtime/PropertyNameArray.h>
#include <wtf/GetPtr.h>

using namespace JSC;

namespace WebCore {

ASSERT_CLASS_FITS_IN_CELL(JSSpeechInputResultList);
/* Hash table */

static const HashTableValue JSSpeechInputResultListTableValues[] =
{
    { "length", DontDelete | ReadOnly, (intptr_t)static_cast<PropertySlot::GetValueFunc>(jsSpeechInputResultListLength), (intptr_t)0, NoIntrinsic },
    { "constructor", DontEnum | ReadOnly, (intptr_t)static_cast<PropertySlot::GetValueFunc>(jsSpeechInputResultListConstructor), (intptr_t)0, NoIntrinsic },
    { 0, 0, 0, 0, NoIntrinsic }
};

static const HashTable JSSpeechInputResultListTable = { 5, 3, JSSpeechInputResultListTableValues, 0 };
/* Hash table for constructor */

static const HashTableValue JSSpeechInputResultListConstructorTableValues[] =
{
    { 0, 0, 0, 0, NoIntrinsic }
};

static const HashTable JSSpeechInputResultListConstructorTable = { 1, 0, JSSpeechInputResultListConstructorTableValues, 0 };
const ClassInfo JSSpeechInputResultListConstructor::s_info = { "SpeechInputResultListConstructor", &Base::s_info, &JSSpeechInputResultListConstructorTable, 0, CREATE_METHOD_TABLE(JSSpeechInputResultListConstructor) };

JSSpeechInputResultListConstructor::JSSpeechInputResultListConstructor(Structure* structure, JSDOMGlobalObject* globalObject)
    : DOMConstructorObject(structure, globalObject)
{
}

void JSSpeechInputResultListConstructor::finishCreation(ExecState* exec, JSDOMGlobalObject* globalObject)
{
    Base::finishCreation(exec->globalData());
    ASSERT(inherits(&s_info));
    putDirect(exec->globalData(), exec->propertyNames().prototype, JSSpeechInputResultListPrototype::self(exec, globalObject), DontDelete | ReadOnly);
}

bool JSSpeechInputResultListConstructor::getOwnPropertySlot(JSCell* cell, ExecState* exec, const Identifier& propertyName, PropertySlot& slot)
{
    return getStaticValueSlot<JSSpeechInputResultListConstructor, JSDOMWrapper>(exec, &JSSpeechInputResultListConstructorTable, static_cast<JSSpeechInputResultListConstructor*>(cell), propertyName, slot);
}

bool JSSpeechInputResultListConstructor::getOwnPropertyDescriptor(JSObject* object, ExecState* exec, const Identifier& propertyName, PropertyDescriptor& descriptor)
{
    return getStaticValueDescriptor<JSSpeechInputResultListConstructor, JSDOMWrapper>(exec, &JSSpeechInputResultListConstructorTable, static_cast<JSSpeechInputResultListConstructor*>(object), propertyName, descriptor);
}

/* Hash table for prototype */

static const HashTableValue JSSpeechInputResultListPrototypeTableValues[] =
{
    { "item", DontDelete | JSC::Function, (intptr_t)static_cast<NativeFunction>(jsSpeechInputResultListPrototypeFunctionItem), (intptr_t)1, NoIntrinsic },
    { 0, 0, 0, 0, NoIntrinsic }
};

static const HashTable JSSpeechInputResultListPrototypeTable = { 2, 1, JSSpeechInputResultListPrototypeTableValues, 0 };
const ClassInfo JSSpeechInputResultListPrototype::s_info = { "SpeechInputResultListPrototype", &Base::s_info, &JSSpeechInputResultListPrototypeTable, 0, CREATE_METHOD_TABLE(JSSpeechInputResultListPrototype) };

JSObject* JSSpeechInputResultListPrototype::self(ExecState* exec, JSGlobalObject* globalObject)
{
    return getDOMPrototype<JSSpeechInputResultList>(exec, globalObject);
}

bool JSSpeechInputResultListPrototype::getOwnPropertySlot(JSCell* cell, ExecState* exec, const Identifier& propertyName, PropertySlot& slot)
{
    JSSpeechInputResultListPrototype* thisObject = jsCast<JSSpeechInputResultListPrototype*>(cell);
    return getStaticFunctionSlot<JSObject>(exec, &JSSpeechInputResultListPrototypeTable, thisObject, propertyName, slot);
}

bool JSSpeechInputResultListPrototype::getOwnPropertyDescriptor(JSObject* object, ExecState* exec, const Identifier& propertyName, PropertyDescriptor& descriptor)
{
    JSSpeechInputResultListPrototype* thisObject = jsCast<JSSpeechInputResultListPrototype*>(object);
    return getStaticFunctionDescriptor<JSObject>(exec, &JSSpeechInputResultListPrototypeTable, thisObject, propertyName, descriptor);
}

const ClassInfo JSSpeechInputResultList::s_info = { "SpeechInputResultList", &Base::s_info, &JSSpeechInputResultListTable, 0 , CREATE_METHOD_TABLE(JSSpeechInputResultList) };

JSSpeechInputResultList::JSSpeechInputResultList(Structure* structure, JSDOMGlobalObject* globalObject, PassRefPtr<SpeechInputResultList> impl)
    : JSDOMWrapper(structure, globalObject)
    , m_impl(impl.leakRef())
{
}

void JSSpeechInputResultList::finishCreation(JSGlobalData& globalData)
{
    Base::finishCreation(globalData);
    ASSERT(inherits(&s_info));
}

JSObject* JSSpeechInputResultList::createPrototype(ExecState* exec, JSGlobalObject* globalObject)
{
    return JSSpeechInputResultListPrototype::create(exec->globalData(), globalObject, JSSpeechInputResultListPrototype::createStructure(globalObject->globalData(), globalObject, globalObject->objectPrototype()));
}

void JSSpeechInputResultList::destroy(JSC::JSCell* cell)
{
    JSSpeechInputResultList* thisObject = jsCast<JSSpeechInputResultList*>(cell);
    thisObject->JSSpeechInputResultList::~JSSpeechInputResultList();
}

JSSpeechInputResultList::~JSSpeechInputResultList()
{
    releaseImplIfNotNull();
}

bool JSSpeechInputResultList::getOwnPropertySlot(JSCell* cell, ExecState* exec, const Identifier& propertyName, PropertySlot& slot)
{
    JSSpeechInputResultList* thisObject = jsCast<JSSpeechInputResultList*>(cell);
    ASSERT_GC_OBJECT_INHERITS(thisObject, &s_info);
    const HashEntry* entry = JSSpeechInputResultListTable.entry(exec, propertyName);
    if (entry) {
        slot.setCustom(thisObject, entry->propertyGetter());
        return true;
    }
    bool ok;
    unsigned index = propertyName.toUInt32(ok);
    if (ok && index < static_cast<SpeechInputResultList*>(thisObject->impl())->length()) {
        slot.setCustomIndex(thisObject, index, indexGetter);
        return true;
    }
    return getStaticValueSlot<JSSpeechInputResultList, Base>(exec, &JSSpeechInputResultListTable, thisObject, propertyName, slot);
}

bool JSSpeechInputResultList::getOwnPropertyDescriptor(JSObject* object, ExecState* exec, const Identifier& propertyName, PropertyDescriptor& descriptor)
{
    JSSpeechInputResultList* thisObject = jsCast<JSSpeechInputResultList*>(object);
    ASSERT_GC_OBJECT_INHERITS(thisObject, &s_info);
    const HashEntry* entry = JSSpeechInputResultListTable.entry(exec, propertyName);
    if (entry) {
        PropertySlot slot;
        slot.setCustom(thisObject, entry->propertyGetter());
        descriptor.setDescriptor(slot.getValue(exec, propertyName), entry->attributes());
        return true;
    }
    bool ok;
    unsigned index = propertyName.toUInt32(ok);
    if (ok && index < static_cast<SpeechInputResultList*>(thisObject->impl())->length()) {
        PropertySlot slot;
        slot.setCustomIndex(thisObject, index, indexGetter);
        descriptor.setDescriptor(slot.getValue(exec, propertyName), DontDelete | ReadOnly);
        return true;
    }
    return getStaticValueDescriptor<JSSpeechInputResultList, Base>(exec, &JSSpeechInputResultListTable, thisObject, propertyName, descriptor);
}

bool JSSpeechInputResultList::getOwnPropertySlotByIndex(JSCell* cell, ExecState* exec, unsigned propertyName, PropertySlot& slot)
{
    JSSpeechInputResultList* thisObject = jsCast<JSSpeechInputResultList*>(cell);
    ASSERT_GC_OBJECT_INHERITS(thisObject, &s_info);
    if (propertyName < static_cast<SpeechInputResultList*>(thisObject->impl())->length()) {
        slot.setCustomIndex(thisObject, propertyName, thisObject->indexGetter);
        return true;
    }
    return thisObject->methodTable()->getOwnPropertySlot(thisObject, exec, Identifier::from(exec, propertyName), slot);
}

JSValue jsSpeechInputResultListLength(ExecState* exec, JSValue slotBase, const Identifier&)
{
    JSSpeechInputResultList* castedThis = static_cast<JSSpeechInputResultList*>(asObject(slotBase));
    UNUSED_PARAM(exec);
    SpeechInputResultList* impl = static_cast<SpeechInputResultList*>(castedThis->impl());
    JSValue result = jsNumber(impl->length());
    return result;
}


JSValue jsSpeechInputResultListConstructor(ExecState* exec, JSValue slotBase, const Identifier&)
{
    JSSpeechInputResultList* domObject = static_cast<JSSpeechInputResultList*>(asObject(slotBase));
    return JSSpeechInputResultList::getConstructor(exec, domObject->globalObject());
}

void JSSpeechInputResultList::getOwnPropertyNames(JSObject* object, ExecState* exec, PropertyNameArray& propertyNames, EnumerationMode mode)
{
    JSSpeechInputResultList* thisObject = jsCast<JSSpeechInputResultList*>(object);
    ASSERT_GC_OBJECT_INHERITS(thisObject, &s_info);
    for (unsigned i = 0; i < static_cast<SpeechInputResultList*>(thisObject->impl())->length(); ++i)
        propertyNames.add(Identifier::from(exec, i));
     Base::getOwnPropertyNames(thisObject, exec, propertyNames, mode);
}

JSValue JSSpeechInputResultList::getConstructor(ExecState* exec, JSGlobalObject* globalObject)
{
    return getDOMConstructor<JSSpeechInputResultListConstructor>(exec, static_cast<JSDOMGlobalObject*>(globalObject));
}

EncodedJSValue JSC_HOST_CALL jsSpeechInputResultListPrototypeFunctionItem(ExecState* exec)
{
    JSValue thisValue = exec->hostThisValue();
    if (!thisValue.inherits(&JSSpeechInputResultList::s_info))
        return throwVMTypeError(exec);
    JSSpeechInputResultList* castedThis = static_cast<JSSpeechInputResultList*>(asObject(thisValue));
    ASSERT_GC_OBJECT_INHERITS(castedThis, &JSSpeechInputResultList::s_info);
    SpeechInputResultList* impl = static_cast<SpeechInputResultList*>(castedThis->impl());
    if (exec->argumentCount() < 1)
        return throwVMError(exec, createTypeError(exec, "Not enough arguments"));
    int index(MAYBE_MISSING_PARAMETER(exec, 0, DefaultIsUndefined).toUInt32(exec));
    if (index < 0) {
        setDOMException(exec, INDEX_SIZE_ERR);
        return JSValue::encode(jsUndefined());
    }
    if (exec->hadException())
        return JSValue::encode(jsUndefined());

    JSC::JSValue result = toJS(exec, castedThis->globalObject(), WTF::getPtr(impl->item(index)));
    return JSValue::encode(result);
}


JSValue JSSpeechInputResultList::indexGetter(ExecState* exec, JSValue slotBase, unsigned index)
{
    JSSpeechInputResultList* thisObj = static_cast<JSSpeechInputResultList*>(asObject(slotBase));
    ASSERT_GC_OBJECT_INHERITS(thisObj, &s_info);
    return toJS(exec, thisObj->globalObject(), static_cast<SpeechInputResultList*>(thisObj->impl())->item(index));
}

static inline bool isObservable(JSSpeechInputResultList* jsSpeechInputResultList)
{
    if (jsSpeechInputResultList->hasCustomProperties())
        return true;
    return false;
}

bool JSSpeechInputResultListOwner::isReachableFromOpaqueRoots(JSC::Handle<JSC::Unknown> handle, void*, SlotVisitor& visitor)
{
    JSSpeechInputResultList* jsSpeechInputResultList = static_cast<JSSpeechInputResultList*>(handle.get().asCell());
    if (!isObservable(jsSpeechInputResultList))
        return false;
    UNUSED_PARAM(visitor);
    return false;
}

void JSSpeechInputResultListOwner::finalize(JSC::Handle<JSC::Unknown> handle, void* context)
{
    JSSpeechInputResultList* jsSpeechInputResultList = static_cast<JSSpeechInputResultList*>(handle.get().asCell());
    DOMWrapperWorld* world = static_cast<DOMWrapperWorld*>(context);
    uncacheWrapper(world, jsSpeechInputResultList->impl(), jsSpeechInputResultList);
    jsSpeechInputResultList->releaseImpl();
}

JSC::JSValue toJS(JSC::ExecState* exec, JSDOMGlobalObject* globalObject, SpeechInputResultList* impl)
{
    return wrap<JSSpeechInputResultList>(exec, globalObject, impl);
}

SpeechInputResultList* toSpeechInputResultList(JSC::JSValue value)
{
    return value.inherits(&JSSpeechInputResultList::s_info) ? static_cast<JSSpeechInputResultList*>(asObject(value))->impl() : 0;
}

}

#endif // ENABLE(INPUT_SPEECH)
