

    [
               Conditional=DISCOVERY,
               Supplemental=Navigator
    ] interface Navigator {

        void getNetworkServices(
        		in DOMString type,
        		in [Callback]  NavServiceOkCB successCallback,
                in [Callback, Optional] NavServiceErrorCB errorCallback );


    };

