module discovery {
	interface [
               Conditional=DISCOVERY,
	           OmitConstructor,
	           ActiveDOMObject,
	           EventTarget
	           ] NavService	{
	           
	    readonly attribute DOMString id;
	    readonly attribute DOMString name;
	    readonly attribute DOMString type;
	    readonly attribute DOMString url;
	    readonly attribute DOMString config;

	    readonly attribute boolean  online;

        attribute EventListener onserviceonline;
        attribute EventListener onserviceoffline;
		attribute EventListener onnotify;
		
        // EventTarget interface
        void addEventListener(in DOMString type,
                              in EventListener listener,
                              in [Optional] boolean useCapture);
        void removeEventListener(in DOMString type,
                                 in EventListener listener,
                                 in [Optional] boolean useCapture);
        boolean dispatchEvent(in Event evt)
            raises(EventException);

	};
}
